run:
  skip-dirs:
    - judge/sources # Test sources of the judge

issues:
  exclude-rules: []

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
