repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/golangci/golangci-lint
    # Pin to a specific golangci-lint release tag
    rev: v2.4.0
    hooks:
      - id: golangci-lint-config-verify
      - id: golangci-lint-full
        name: golangci-lint
        entry: >
          golangci-lint run -c .golangci.yml --fix
          ./restapi/...
          ./api/...
          ./database/...
          ./judge/...
          ./langs/...
          ./migrator/...
          ./executor/...
          ./integration/...
          ./storage/...
          ./uploader/...
          ./utils/...
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
