FROM golang:1.24 as builder

WORKDIR /go/src/github.com/yosupo06/library-checker-judge/migrator

COPY ./migrator/go.mod /go/src/github.com/yosupo06/library-checker-judge/migrator/
COPY ./migrator/go.sum /go/src/github.com/yosupo06/library-checker-judge/migrator/

COPY ./database/go.mod /go/src/github.com/yosupo06/library-checker-judge/database/
COPY ./database/go.sum /go/src/github.com/yosupo06/library-checker-judge/database/

RUN go mod download

COPY ./migrator/. /go/src/github.com/yosupo06/library-checker-judge/migrator/
COPY ./database/. /go/src/github.com/yosupo06/library-checker-judge/database/

RUN CGO_ENABLED=0 GOOS=linux go build .

FROM alpine
RUN apk --no-cache add ca-certificates

WORKDIR /root/
COPY --from=builder /go/src/github.com/yosupo06/library-checker-judge/migrator/migrator .

ENTRYPOINT ["./migrator"]
