FROM golang:1.18 as builder

WORKDIR /go/src/github.com/yosupo06/library-checker-judge/api

COPY ./api/go.mod /go/src/github.com/yosupo06/library-checker-judge/api/
COPY ./api/go.sum /go/src/github.com/yosupo06/library-checker-judge/api/

COPY ./database/go.mod /go/src/github.com/yosupo06/library-checker-judge/database/
COPY ./database/go.sum /go/src/github.com/yosupo06/library-checker-judge/database/

RUN go mod download

COPY ./api/. /go/src/github.com/yosupo06/library-checker-judge/api/
COPY ./database/. /go/src/github.com/yosupo06/library-checker-judge/database/

RUN CGO_ENABLED=0 GOOS=linux go build .

FROM alpine as grpc_health_probe_getter
RUN GRPC_HEALTH_PROBE_VERSION=v0.4.11 && \
    wget -qO/tmp/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 && \
    chmod +x /tmp/grpc_health_probe

FROM alpine
RUN apk --no-cache add ca-certificates

WORKDIR /root/
COPY --from=builder /go/src/github.com/yosupo06/library-checker-judge/api/api .
COPY ./api/api.sh .
COPY ./langs/langs.toml .
COPY --from=grpc_health_probe_getter /tmp/grpc_health_probe /bin/grpc_health_probe

ENV FIREBASE_PROJECT=dev-library-checker-project
ENTRYPOINT ["./api", "--langs=./langs.toml"]
