version: '2'

services:
  api:
    build:
      dockerfile: Dockerfile.API
    ports:
      - 12380:12380
    depends_on:
      db-init:
        condition: service_completed_successfully
      create-minio-bucket:
        condition: service_completed_successfully
    environment:
      - API_DB_LOG=true
      - PG_HOST=db
      - PG_TABLE=librarychecker
      - PG_USER=postgres
      - PG_PASS=passwd
      - FIREBASE_AUTH_EMULATOR_HOST=firebase:9099
    healthcheck:
        test: wget -q -O - localhost:12380/health || exit 1
        timeout: 10s
        interval: 1s
        retries: 30

  db:
    image: postgres:11.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=librarychecker
      - POSTGRES_PASSWORD=passwd
    healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "librarychecker", "-U", "postgres" ]
        timeout: 10s
        interval: 1s
        retries: 30
  db-init:
    build:
      dockerfile: Dockerfile.MIGRATOR
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRE_HOST=db
      - POSTGRE_TABLE=librarychecker
      - POSTGRE_USER=postgres
      - POSTGRE_PASS=passwd

  minio:
    image: minio/minio
    command: server /data --console-address :9001
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniopass
  create-minio-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minio miniopass;
      /usr/bin/mc rm --recursive --force myminio/testcase;
      /usr/bin/mc rm --recursive --force myminio/testcase-public;
      /usr/bin/mc mb myminio/testcase;
      /usr/bin/mc mb myminio/testcase-public;
      /usr/bin/mc policy download myminio/testcase;
      /usr/bin/mc policy download myminio/testcase-public;
      /usr/bin/mc anonymous set public myminio/testcase-public;
      exit 0;
      "

  firebase:
    build:
      dockerfile: Dockerfile.Firebase
    ports:
      - 4000:4000
      - 9099:9099
    volumes:
      - ./firebase.json:/opt/firebase/firebase.json
    working_dir: /opt/firebase
    command: "firebase emulators:start --project library-checker-project"    
    tty: true
