FROM ekidd/rust-musl-builder:latest as init-builder
COPY --chown=rust:rust init .
RUN cargo build --release

FROM mcr.microsoft.com/dotnet/sdk:7.0

ENV DOTNET_EnableWriteXorExecute=0
RUN dotnet new console -o /opt/C-Sharp
COPY C-Sharp.csproj /opt/C-Sharp
RUN dotnet restore /opt/C-Sharp -r linux-x64

COPY --from=init-builder /home/rust/src/target/x86_64-unknown-linux-musl/release/library-checker-init /usr/bin

LABEL library-checker-image=true
