FROM ubuntu as builder

RUN apt-get update
RUN apt-get install -y git
WORKDIR /workdir
RUN git clone https://github.com/atcoder/ac-library/ -b v1.4

FROM gcc:12.1
COPY --from=builder /workdir/ac-library/atcoder /opt/ac-library/atcoder
