// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	FirebaseAuthScopes = "firebaseAuth.Scopes"
)

// Defines values for SolvedStatus.
const (
	AC       SolvedStatus = "AC"
	LATESTAC SolvedStatus = "LATEST_AC"
)

// Defines values for SubmissionOrder.
const (
	MinusId  SubmissionOrder = "-id"
	PlusTime SubmissionOrder = "+time"
)

// ChangeCurrentUserInfoRequest defines model for ChangeCurrentUserInfoRequest.
type ChangeCurrentUserInfoRequest struct {
	User User `json:"user"`
}

// ChangeCurrentUserInfoResponse defines model for ChangeCurrentUserInfoResponse.
type ChangeCurrentUserInfoResponse = map[string]interface{}

// CreateHackRequest defines model for CreateHackRequest.
type CreateHackRequest struct {
	Submission  int32   `json:"submission"`
	TestCaseCpp *[]byte `json:"test_case_cpp,omitempty"`
	TestCaseTxt *[]byte `json:"test_case_txt,omitempty"`
}

// CurrentUserInfoResponse defines model for CurrentUserInfoResponse.
type CurrentUserInfoResponse struct {
	User *User `json:"user,omitempty"`
}

// HackInfoResponse defines model for HackInfoResponse.
type HackInfoResponse struct {
	JudgeOutput *[]byte      `json:"judge_output,omitempty"`
	Overview    HackOverview `json:"overview"`
	Stderr      *[]byte      `json:"stderr,omitempty"`
	TestCaseCpp *[]byte      `json:"test_case_cpp,omitempty"`
	TestCaseTxt *[]byte      `json:"test_case_txt,omitempty"`
}

// HackListResponse defines model for HackListResponse.
type HackListResponse struct {
	Count int32          `json:"count"`
	Hacks []HackOverview `json:"hacks"`
}

// HackOverview defines model for HackOverview.
type HackOverview struct {
	HackTime     time.Time `json:"hack_time"`
	Id           int32     `json:"id"`
	Memory       *int64    `json:"memory,omitempty"`
	Status       string    `json:"status"`
	SubmissionId int32     `json:"submission_id"`
	Time         *float32  `json:"time,omitempty"`
	UserName     *string   `json:"user_name,omitempty"`
}

// HackResponse defines model for HackResponse.
type HackResponse struct {
	Id int32 `json:"id"`
}

// Lang defines model for Lang.
type Lang struct {
	Id      string `json:"id"`
	Name    string `json:"name"`
	Version string `json:"version"`
}

// LangListResponse defines model for LangListResponse.
type LangListResponse struct {
	Langs []Lang `json:"langs"`
}

// LibraryUrl Optional URL for the user's library profile. Use an empty string to keep it unset.
type LibraryUrl = string

// MonitoringResponse defines model for MonitoringResponse.
type MonitoringResponse struct {
	TaskQueue        TaskQueueInfo `json:"task_queue"`
	TotalSubmissions int32         `json:"total_submissions"`
	TotalUsers       int32         `json:"total_users"`
}

// Problem defines model for Problem.
type Problem struct {
	// Name Problem identifier consisting of lowercase letters, digits, or underscores.
	Name  ProblemName `json:"name"`
	Title string      `json:"title"`
}

// ProblemCategoriesResponse defines model for ProblemCategoriesResponse.
type ProblemCategoriesResponse struct {
	Categories []ProblemCategory `json:"categories"`
}

// ProblemCategory defines model for ProblemCategory.
type ProblemCategory struct {
	Problems []ProblemName `json:"problems"`
	Title    string        `json:"title"`
}

// ProblemInfoResponse defines model for ProblemInfoResponse.
type ProblemInfoResponse struct {
	OverallVersion string `json:"overall_version"`

	// SourceUrl External reference for the problem statement.
	SourceUrl        string  `json:"source_url"`
	TestcasesVersion string  `json:"testcases_version"`
	TimeLimit        float32 `json:"time_limit"`
	Title            string  `json:"title"`
	Version          string  `json:"version"`
}

// ProblemListResponse defines model for ProblemListResponse.
type ProblemListResponse struct {
	Problems []Problem `json:"problems"`
}

// ProblemName Problem identifier consisting of lowercase letters, digits, or underscores.
type ProblemName = string

// RankingResponse defines model for RankingResponse.
type RankingResponse struct {
	Count      int32            `json:"count"`
	Statistics []UserStatistics `json:"statistics"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Name Unique user identifier consisting of letters, digits, hyphen, or underscore.
	Name Username `json:"name"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse = map[string]interface{}

// RejudgeResponse defines model for RejudgeResponse.
type RejudgeResponse = map[string]interface{}

// SolvedStatus Solved status for a problem.
type SolvedStatus string

// SubmissionCaseResult defines model for SubmissionCaseResult.
type SubmissionCaseResult struct {
	Case       string  `json:"case"`
	CheckerOut *[]byte `json:"checker_out,omitempty"`
	Memory     int64   `json:"memory"`
	Status     string  `json:"status"`
	Stderr     *[]byte `json:"stderr,omitempty"`
	Time       float32 `json:"time"`
}

// SubmissionInfoResponse defines model for SubmissionInfoResponse.
type SubmissionInfoResponse struct {
	CanRejudge   bool                    `json:"can_rejudge"`
	CaseResults  *[]SubmissionCaseResult `json:"case_results,omitempty"`
	CompileError *[]byte                 `json:"compile_error,omitempty"`
	Overview     SubmissionOverview      `json:"overview"`
	Source       string                  `json:"source"`
}

// SubmissionListResponse defines model for SubmissionListResponse.
type SubmissionListResponse struct {
	Count       int32                `json:"count"`
	Submissions []SubmissionOverview `json:"submissions"`
}

// SubmissionOrder Sorting order for submissions.
type SubmissionOrder string

// SubmissionOverview defines model for SubmissionOverview.
type SubmissionOverview struct {
	Id             int32      `json:"id"`
	IsLatest       bool       `json:"is_latest"`
	Lang           string     `json:"lang"`
	Memory         int64      `json:"memory"`
	ProblemName    string     `json:"problem_name"`
	ProblemTitle   string     `json:"problem_title"`
	Status         string     `json:"status"`
	SubmissionTime *time.Time `json:"submission_time,omitempty"`
	Time           float32    `json:"time"`
	UserName       *string    `json:"user_name,omitempty"`
}

// SubmitRequest defines model for SubmitRequest.
type SubmitRequest struct {
	Lang string `json:"lang"`

	// Problem Problem identifier consisting of lowercase letters, digits, or underscores.
	Problem ProblemName `json:"problem"`

	// Source Source code to judge (max 1 MiB).
	Source      string `json:"source"`
	TleKnockout *bool  `json:"tle_knockout,omitempty"`
}

// SubmitResponse defines model for SubmitResponse.
type SubmitResponse struct {
	Id int32 `json:"id"`
}

// TaskQueueInfo defines model for TaskQueueInfo.
type TaskQueueInfo struct {
	PendingTasks int32 `json:"pending_tasks"`
	RunningTasks int32 `json:"running_tasks"`
	TotalTasks   int32 `json:"total_tasks"`
}

// User defines model for User.
type User struct {
	IsDeveloper bool `json:"is_developer"`

	// LibraryUrl Optional URL for the user's library profile. Use an empty string to keep it unset.
	LibraryUrl LibraryUrl `json:"library_url"`

	// Name Unique user identifier consisting of letters, digits, hyphen, or underscore.
	Name Username `json:"name"`
}

// UserInfoResponse defines model for UserInfoResponse.
type UserInfoResponse struct {
	User User `json:"user"`
}

// UserSolvedStatisticsResponse defines model for UserSolvedStatisticsResponse.
type UserSolvedStatisticsResponse struct {
	SolvedMap map[string]SolvedStatus `json:"solved_map"`
}

// UserStatistics defines model for UserStatistics.
type UserStatistics struct {
	Count int32 `json:"count"`

	// Name Unique user identifier consisting of letters, digits, hyphen, or underscore.
	Name Username `json:"name"`
}

// Username Unique user identifier consisting of letters, digits, hyphen, or underscore.
type Username = string

// HackId defines model for HackId.
type HackId = int32

// HackLimit defines model for HackLimit.
type HackLimit = int32

// HackSkip defines model for HackSkip.
type HackSkip = int32

// RankingLimit defines model for RankingLimit.
type RankingLimit = int32

// RankingSkip defines model for RankingSkip.
type RankingSkip = int32

// SubmissionId defines model for SubmissionId.
type SubmissionId = int32

// SubmissionLimit defines model for SubmissionLimit.
type SubmissionLimit = int32

// SubmissionSkip defines model for SubmissionSkip.
type SubmissionSkip = int32

// UserNamePath Unique user identifier consisting of letters, digits, hyphen, or underscore.
type UserNamePath = Username

// GetHackListParams defines parameters for GetHackList.
type GetHackListParams struct {
	// Skip Number of hacks to skip before collecting results.
	Skip *HackSkip `form:"skip,omitempty" json:"skip,omitempty"`

	// Limit Maximum number of hacks to return (1-1000).
	Limit  *HackLimit `form:"limit,omitempty" json:"limit,omitempty"`
	User   *string    `form:"user,omitempty" json:"user,omitempty"`
	Status *string    `form:"status,omitempty" json:"status,omitempty"`
	Order  *string    `form:"order,omitempty" json:"order,omitempty"`
}

// GetRankingParams defines parameters for GetRanking.
type GetRankingParams struct {
	// Skip Number of ranking records to skip before collecting results.
	Skip *RankingSkip `form:"skip,omitempty" json:"skip,omitempty"`

	// Limit Maximum number of ranking records to return (1-1000).
	Limit *RankingLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSubmissionListParams defines parameters for GetSubmissionList.
type GetSubmissionListParams struct {
	// Skip Number of submissions to skip before collecting results.
	Skip *SubmissionSkip `form:"skip,omitempty" json:"skip,omitempty"`

	// Limit Maximum number of submissions to return (1-1000).
	Limit     *SubmissionLimit `form:"limit,omitempty" json:"limit,omitempty"`
	Problem   *ProblemName     `form:"problem,omitempty" json:"problem,omitempty"`
	Status    *string          `form:"status,omitempty" json:"status,omitempty"`
	Hacked    *bool            `form:"hacked,omitempty" json:"hacked,omitempty"`
	User      *Username        `form:"user,omitempty" json:"user,omitempty"`
	DedupUser *bool            `form:"dedupUser,omitempty" json:"dedupUser,omitempty"`
	Lang      *string          `form:"lang,omitempty" json:"lang,omitempty"`
	Order     *SubmissionOrder `form:"order,omitempty" json:"order,omitempty"`
}

// PatchCurrentUserInfoJSONRequestBody defines body for PatchCurrentUserInfo for application/json ContentType.
type PatchCurrentUserInfoJSONRequestBody = ChangeCurrentUserInfoRequest

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody = RegisterRequest

// PostHackJSONRequestBody defines body for PostHack for application/json ContentType.
type PostHackJSONRequestBody = CreateHackRequest

// PostSubmitJSONRequestBody defines body for PostSubmit for application/json ContentType.
type PostSubmitJSONRequestBody = SubmitRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get current user info
	// (GET /auth/current_user)
	GetCurrentUserInfo(w http.ResponseWriter, r *http.Request)
	// Change current user info
	// (PATCH /auth/current_user)
	PatchCurrentUserInfo(w http.ResponseWriter, r *http.Request)
	// Register user
	// (POST /auth/register)
	PostRegister(w http.ResponseWriter, r *http.Request)
	// Get problem categories
	// (GET /categories)
	GetProblemCategories(w http.ResponseWriter, r *http.Request)
	// List hacks
	// (GET /hacks)
	GetHackList(w http.ResponseWriter, r *http.Request, params GetHackListParams)
	// Submit hack test case
	// (POST /hacks)
	PostHack(w http.ResponseWriter, r *http.Request)
	// Get hack info
	// (GET /hacks/{id})
	GetHackInfo(w http.ResponseWriter, r *http.Request, id HackId)
	// Get language list
	// (GET /langs)
	GetLangList(w http.ResponseWriter, r *http.Request)
	// Get monitoring data
	// (GET /monitoring)
	GetMonitoring(w http.ResponseWriter, r *http.Request)
	// Get problems
	// (GET /problems)
	GetProblems(w http.ResponseWriter, r *http.Request)
	// Get problem info
	// (GET /problems/{name})
	GetProblemInfo(w http.ResponseWriter, r *http.Request, name ProblemName)
	// Get ranking
	// (GET /ranking)
	GetRanking(w http.ResponseWriter, r *http.Request, params GetRankingParams)
	// Get submissions list
	// (GET /submissions)
	GetSubmissionList(w http.ResponseWriter, r *http.Request, params GetSubmissionListParams)
	// Get submission info
	// (GET /submissions/{id})
	GetSubmissionInfo(w http.ResponseWriter, r *http.Request, id SubmissionId)
	// Rejudge a submission
	// (POST /submissions/{id}/rejudge)
	PostRejudge(w http.ResponseWriter, r *http.Request, id SubmissionId)
	// Submit a solution
	// (POST /submit)
	PostSubmit(w http.ResponseWriter, r *http.Request)
	// Get user info
	// (GET /users/{name})
	GetUserInfo(w http.ResponseWriter, r *http.Request, name UserNamePath)
	// Get user solved statistics
	// (GET /users/{name}/statistics)
	GetUserStatistics(w http.ResponseWriter, r *http.Request, name UserNamePath)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get current user info
// (GET /auth/current_user)
func (_ Unimplemented) GetCurrentUserInfo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Change current user info
// (PATCH /auth/current_user)
func (_ Unimplemented) PatchCurrentUserInfo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register user
// (POST /auth/register)
func (_ Unimplemented) PostRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get problem categories
// (GET /categories)
func (_ Unimplemented) GetProblemCategories(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List hacks
// (GET /hacks)
func (_ Unimplemented) GetHackList(w http.ResponseWriter, r *http.Request, params GetHackListParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit hack test case
// (POST /hacks)
func (_ Unimplemented) PostHack(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get hack info
// (GET /hacks/{id})
func (_ Unimplemented) GetHackInfo(w http.ResponseWriter, r *http.Request, id HackId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get language list
// (GET /langs)
func (_ Unimplemented) GetLangList(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get monitoring data
// (GET /monitoring)
func (_ Unimplemented) GetMonitoring(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get problems
// (GET /problems)
func (_ Unimplemented) GetProblems(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get problem info
// (GET /problems/{name})
func (_ Unimplemented) GetProblemInfo(w http.ResponseWriter, r *http.Request, name ProblemName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get ranking
// (GET /ranking)
func (_ Unimplemented) GetRanking(w http.ResponseWriter, r *http.Request, params GetRankingParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get submissions list
// (GET /submissions)
func (_ Unimplemented) GetSubmissionList(w http.ResponseWriter, r *http.Request, params GetSubmissionListParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get submission info
// (GET /submissions/{id})
func (_ Unimplemented) GetSubmissionInfo(w http.ResponseWriter, r *http.Request, id SubmissionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rejudge a submission
// (POST /submissions/{id}/rejudge)
func (_ Unimplemented) PostRejudge(w http.ResponseWriter, r *http.Request, id SubmissionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit a solution
// (POST /submit)
func (_ Unimplemented) PostSubmit(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user info
// (GET /users/{name})
func (_ Unimplemented) GetUserInfo(w http.ResponseWriter, r *http.Request, name UserNamePath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user solved statistics
// (GET /users/{name}/statistics)
func (_ Unimplemented) GetUserStatistics(w http.ResponseWriter, r *http.Request, name UserNamePath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCurrentUserInfo operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUserInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUserInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchCurrentUserInfo operation middleware
func (siw *ServerInterfaceWrapper) PatchCurrentUserInfo(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, FirebaseAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchCurrentUserInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRegister operation middleware
func (siw *ServerInterfaceWrapper) PostRegister(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, FirebaseAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProblemCategories operation middleware
func (siw *ServerInterfaceWrapper) GetProblemCategories(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProblemCategories(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHackList operation middleware
func (siw *ServerInterfaceWrapper) GetHackList(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHackListParams

	// ------------- Optional query parameter "skip" -------------

	err = runtime.BindQueryParameter("form", true, false, "skip", r.URL.Query(), &params.Skip)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "skip", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "user" -------------

	err = runtime.BindQueryParameter("form", true, false, "user", r.URL.Query(), &params.User)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHackList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostHack operation middleware
func (siw *ServerInterfaceWrapper) PostHack(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, FirebaseAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostHack(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHackInfo operation middleware
func (siw *ServerInterfaceWrapper) GetHackInfo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id HackId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHackInfo(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLangList operation middleware
func (siw *ServerInterfaceWrapper) GetLangList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLangList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMonitoring operation middleware
func (siw *ServerInterfaceWrapper) GetMonitoring(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMonitoring(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProblems operation middleware
func (siw *ServerInterfaceWrapper) GetProblems(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProblems(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProblemInfo operation middleware
func (siw *ServerInterfaceWrapper) GetProblemInfo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name ProblemName

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProblemInfo(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRanking operation middleware
func (siw *ServerInterfaceWrapper) GetRanking(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRankingParams

	// ------------- Optional query parameter "skip" -------------

	err = runtime.BindQueryParameter("form", true, false, "skip", r.URL.Query(), &params.Skip)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "skip", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRanking(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubmissionList operation middleware
func (siw *ServerInterfaceWrapper) GetSubmissionList(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSubmissionListParams

	// ------------- Optional query parameter "skip" -------------

	err = runtime.BindQueryParameter("form", true, false, "skip", r.URL.Query(), &params.Skip)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "skip", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "problem" -------------

	err = runtime.BindQueryParameter("form", true, false, "problem", r.URL.Query(), &params.Problem)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "problem", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "hacked" -------------

	err = runtime.BindQueryParameter("form", true, false, "hacked", r.URL.Query(), &params.Hacked)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hacked", Err: err})
		return
	}

	// ------------- Optional query parameter "user" -------------

	err = runtime.BindQueryParameter("form", true, false, "user", r.URL.Query(), &params.User)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user", Err: err})
		return
	}

	// ------------- Optional query parameter "dedupUser" -------------

	err = runtime.BindQueryParameter("form", true, false, "dedupUser", r.URL.Query(), &params.DedupUser)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dedupUser", Err: err})
		return
	}

	// ------------- Optional query parameter "lang" -------------

	err = runtime.BindQueryParameter("form", true, false, "lang", r.URL.Query(), &params.Lang)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lang", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubmissionList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubmissionInfo operation middleware
func (siw *ServerInterfaceWrapper) GetSubmissionInfo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id SubmissionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubmissionInfo(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRejudge operation middleware
func (siw *ServerInterfaceWrapper) PostRejudge(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id SubmissionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, FirebaseAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRejudge(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSubmit operation middleware
func (siw *ServerInterfaceWrapper) PostSubmit(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, FirebaseAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSubmit(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserInfo operation middleware
func (siw *ServerInterfaceWrapper) GetUserInfo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name UserNamePath

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserInfo(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserStatistics operation middleware
func (siw *ServerInterfaceWrapper) GetUserStatistics(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name UserNamePath

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserStatistics(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/current_user", wrapper.GetCurrentUserInfo)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/auth/current_user", wrapper.PatchCurrentUserInfo)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.PostRegister)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/categories", wrapper.GetProblemCategories)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/hacks", wrapper.GetHackList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/hacks", wrapper.PostHack)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/hacks/{id}", wrapper.GetHackInfo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/langs", wrapper.GetLangList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/monitoring", wrapper.GetMonitoring)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/problems", wrapper.GetProblems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/problems/{name}", wrapper.GetProblemInfo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ranking", wrapper.GetRanking)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/submissions", wrapper.GetSubmissionList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/submissions/{id}", wrapper.GetSubmissionInfo)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/submissions/{id}/rejudge", wrapper.PostRejudge)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/submit", wrapper.PostSubmit)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{name}", wrapper.GetUserInfo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{name}/statistics", wrapper.GetUserStatistics)
	})

	return r
}

type GetCurrentUserInfoRequestObject struct {
}

type GetCurrentUserInfoResponseObject interface {
	VisitGetCurrentUserInfoResponse(w http.ResponseWriter) error
}

type GetCurrentUserInfo200JSONResponse CurrentUserInfoResponse

func (response GetCurrentUserInfo200JSONResponse) VisitGetCurrentUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchCurrentUserInfoRequestObject struct {
	Body *PatchCurrentUserInfoJSONRequestBody
}

type PatchCurrentUserInfoResponseObject interface {
	VisitPatchCurrentUserInfoResponse(w http.ResponseWriter) error
}

type PatchCurrentUserInfo200JSONResponse ChangeCurrentUserInfoResponse

func (response PatchCurrentUserInfo200JSONResponse) VisitPatchCurrentUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostRegisterRequestObject struct {
	Body *PostRegisterJSONRequestBody
}

type PostRegisterResponseObject interface {
	VisitPostRegisterResponse(w http.ResponseWriter) error
}

type PostRegister200JSONResponse RegisterResponse

func (response PostRegister200JSONResponse) VisitPostRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProblemCategoriesRequestObject struct {
}

type GetProblemCategoriesResponseObject interface {
	VisitGetProblemCategoriesResponse(w http.ResponseWriter) error
}

type GetProblemCategories200JSONResponse ProblemCategoriesResponse

func (response GetProblemCategories200JSONResponse) VisitGetProblemCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHackListRequestObject struct {
	Params GetHackListParams
}

type GetHackListResponseObject interface {
	VisitGetHackListResponse(w http.ResponseWriter) error
}

type GetHackList200JSONResponse HackListResponse

func (response GetHackList200JSONResponse) VisitGetHackListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostHackRequestObject struct {
	Body *PostHackJSONRequestBody
}

type PostHackResponseObject interface {
	VisitPostHackResponse(w http.ResponseWriter) error
}

type PostHack200JSONResponse HackResponse

func (response PostHack200JSONResponse) VisitPostHackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHackInfoRequestObject struct {
	Id HackId `json:"id"`
}

type GetHackInfoResponseObject interface {
	VisitGetHackInfoResponse(w http.ResponseWriter) error
}

type GetHackInfo200JSONResponse HackInfoResponse

func (response GetHackInfo200JSONResponse) VisitGetHackInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLangListRequestObject struct {
}

type GetLangListResponseObject interface {
	VisitGetLangListResponse(w http.ResponseWriter) error
}

type GetLangList200JSONResponse LangListResponse

func (response GetLangList200JSONResponse) VisitGetLangListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMonitoringRequestObject struct {
}

type GetMonitoringResponseObject interface {
	VisitGetMonitoringResponse(w http.ResponseWriter) error
}

type GetMonitoring200JSONResponse MonitoringResponse

func (response GetMonitoring200JSONResponse) VisitGetMonitoringResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProblemsRequestObject struct {
}

type GetProblemsResponseObject interface {
	VisitGetProblemsResponse(w http.ResponseWriter) error
}

type GetProblems200JSONResponse ProblemListResponse

func (response GetProblems200JSONResponse) VisitGetProblemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProblemInfoRequestObject struct {
	Name ProblemName `json:"name"`
}

type GetProblemInfoResponseObject interface {
	VisitGetProblemInfoResponse(w http.ResponseWriter) error
}

type GetProblemInfo200JSONResponse ProblemInfoResponse

func (response GetProblemInfo200JSONResponse) VisitGetProblemInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRankingRequestObject struct {
	Params GetRankingParams
}

type GetRankingResponseObject interface {
	VisitGetRankingResponse(w http.ResponseWriter) error
}

type GetRanking200JSONResponse RankingResponse

func (response GetRanking200JSONResponse) VisitGetRankingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSubmissionListRequestObject struct {
	Params GetSubmissionListParams
}

type GetSubmissionListResponseObject interface {
	VisitGetSubmissionListResponse(w http.ResponseWriter) error
}

type GetSubmissionList200JSONResponse SubmissionListResponse

func (response GetSubmissionList200JSONResponse) VisitGetSubmissionListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSubmissionInfoRequestObject struct {
	Id SubmissionId `json:"id"`
}

type GetSubmissionInfoResponseObject interface {
	VisitGetSubmissionInfoResponse(w http.ResponseWriter) error
}

type GetSubmissionInfo200JSONResponse SubmissionInfoResponse

func (response GetSubmissionInfo200JSONResponse) VisitGetSubmissionInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostRejudgeRequestObject struct {
	Id SubmissionId `json:"id"`
}

type PostRejudgeResponseObject interface {
	VisitPostRejudgeResponse(w http.ResponseWriter) error
}

type PostRejudge200JSONResponse RejudgeResponse

func (response PostRejudge200JSONResponse) VisitPostRejudgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSubmitRequestObject struct {
	Body *PostSubmitJSONRequestBody
}

type PostSubmitResponseObject interface {
	VisitPostSubmitResponse(w http.ResponseWriter) error
}

type PostSubmit200JSONResponse SubmitResponse

func (response PostSubmit200JSONResponse) VisitPostSubmitResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserInfoRequestObject struct {
	Name UserNamePath `json:"name"`
}

type GetUserInfoResponseObject interface {
	VisitGetUserInfoResponse(w http.ResponseWriter) error
}

type GetUserInfo200JSONResponse UserInfoResponse

func (response GetUserInfo200JSONResponse) VisitGetUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserStatisticsRequestObject struct {
	Name UserNamePath `json:"name"`
}

type GetUserStatisticsResponseObject interface {
	VisitGetUserStatisticsResponse(w http.ResponseWriter) error
}

type GetUserStatistics200JSONResponse UserSolvedStatisticsResponse

func (response GetUserStatistics200JSONResponse) VisitGetUserStatisticsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get current user info
	// (GET /auth/current_user)
	GetCurrentUserInfo(ctx context.Context, request GetCurrentUserInfoRequestObject) (GetCurrentUserInfoResponseObject, error)
	// Change current user info
	// (PATCH /auth/current_user)
	PatchCurrentUserInfo(ctx context.Context, request PatchCurrentUserInfoRequestObject) (PatchCurrentUserInfoResponseObject, error)
	// Register user
	// (POST /auth/register)
	PostRegister(ctx context.Context, request PostRegisterRequestObject) (PostRegisterResponseObject, error)
	// Get problem categories
	// (GET /categories)
	GetProblemCategories(ctx context.Context, request GetProblemCategoriesRequestObject) (GetProblemCategoriesResponseObject, error)
	// List hacks
	// (GET /hacks)
	GetHackList(ctx context.Context, request GetHackListRequestObject) (GetHackListResponseObject, error)
	// Submit hack test case
	// (POST /hacks)
	PostHack(ctx context.Context, request PostHackRequestObject) (PostHackResponseObject, error)
	// Get hack info
	// (GET /hacks/{id})
	GetHackInfo(ctx context.Context, request GetHackInfoRequestObject) (GetHackInfoResponseObject, error)
	// Get language list
	// (GET /langs)
	GetLangList(ctx context.Context, request GetLangListRequestObject) (GetLangListResponseObject, error)
	// Get monitoring data
	// (GET /monitoring)
	GetMonitoring(ctx context.Context, request GetMonitoringRequestObject) (GetMonitoringResponseObject, error)
	// Get problems
	// (GET /problems)
	GetProblems(ctx context.Context, request GetProblemsRequestObject) (GetProblemsResponseObject, error)
	// Get problem info
	// (GET /problems/{name})
	GetProblemInfo(ctx context.Context, request GetProblemInfoRequestObject) (GetProblemInfoResponseObject, error)
	// Get ranking
	// (GET /ranking)
	GetRanking(ctx context.Context, request GetRankingRequestObject) (GetRankingResponseObject, error)
	// Get submissions list
	// (GET /submissions)
	GetSubmissionList(ctx context.Context, request GetSubmissionListRequestObject) (GetSubmissionListResponseObject, error)
	// Get submission info
	// (GET /submissions/{id})
	GetSubmissionInfo(ctx context.Context, request GetSubmissionInfoRequestObject) (GetSubmissionInfoResponseObject, error)
	// Rejudge a submission
	// (POST /submissions/{id}/rejudge)
	PostRejudge(ctx context.Context, request PostRejudgeRequestObject) (PostRejudgeResponseObject, error)
	// Submit a solution
	// (POST /submit)
	PostSubmit(ctx context.Context, request PostSubmitRequestObject) (PostSubmitResponseObject, error)
	// Get user info
	// (GET /users/{name})
	GetUserInfo(ctx context.Context, request GetUserInfoRequestObject) (GetUserInfoResponseObject, error)
	// Get user solved statistics
	// (GET /users/{name}/statistics)
	GetUserStatistics(ctx context.Context, request GetUserStatisticsRequestObject) (GetUserStatisticsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetCurrentUserInfo operation middleware
func (sh *strictHandler) GetCurrentUserInfo(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentUserInfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUserInfo(ctx, request.(GetCurrentUserInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUserInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentUserInfoResponseObject); ok {
		if err := validResponse.VisitGetCurrentUserInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchCurrentUserInfo operation middleware
func (sh *strictHandler) PatchCurrentUserInfo(w http.ResponseWriter, r *http.Request) {
	var request PatchCurrentUserInfoRequestObject

	var body PatchCurrentUserInfoJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchCurrentUserInfo(ctx, request.(PatchCurrentUserInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchCurrentUserInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchCurrentUserInfoResponseObject); ok {
		if err := validResponse.VisitPatchCurrentUserInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostRegister operation middleware
func (sh *strictHandler) PostRegister(w http.ResponseWriter, r *http.Request) {
	var request PostRegisterRequestObject

	var body PostRegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostRegister(ctx, request.(PostRegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostRegister")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostRegisterResponseObject); ok {
		if err := validResponse.VisitPostRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProblemCategories operation middleware
func (sh *strictHandler) GetProblemCategories(w http.ResponseWriter, r *http.Request) {
	var request GetProblemCategoriesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProblemCategories(ctx, request.(GetProblemCategoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProblemCategories")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProblemCategoriesResponseObject); ok {
		if err := validResponse.VisitGetProblemCategoriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHackList operation middleware
func (sh *strictHandler) GetHackList(w http.ResponseWriter, r *http.Request, params GetHackListParams) {
	var request GetHackListRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHackList(ctx, request.(GetHackListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHackList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHackListResponseObject); ok {
		if err := validResponse.VisitGetHackListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostHack operation middleware
func (sh *strictHandler) PostHack(w http.ResponseWriter, r *http.Request) {
	var request PostHackRequestObject

	var body PostHackJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostHack(ctx, request.(PostHackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostHack")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostHackResponseObject); ok {
		if err := validResponse.VisitPostHackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHackInfo operation middleware
func (sh *strictHandler) GetHackInfo(w http.ResponseWriter, r *http.Request, id HackId) {
	var request GetHackInfoRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHackInfo(ctx, request.(GetHackInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHackInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHackInfoResponseObject); ok {
		if err := validResponse.VisitGetHackInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLangList operation middleware
func (sh *strictHandler) GetLangList(w http.ResponseWriter, r *http.Request) {
	var request GetLangListRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLangList(ctx, request.(GetLangListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLangList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLangListResponseObject); ok {
		if err := validResponse.VisitGetLangListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMonitoring operation middleware
func (sh *strictHandler) GetMonitoring(w http.ResponseWriter, r *http.Request) {
	var request GetMonitoringRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMonitoring(ctx, request.(GetMonitoringRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMonitoring")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMonitoringResponseObject); ok {
		if err := validResponse.VisitGetMonitoringResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProblems operation middleware
func (sh *strictHandler) GetProblems(w http.ResponseWriter, r *http.Request) {
	var request GetProblemsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProblems(ctx, request.(GetProblemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProblems")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProblemsResponseObject); ok {
		if err := validResponse.VisitGetProblemsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProblemInfo operation middleware
func (sh *strictHandler) GetProblemInfo(w http.ResponseWriter, r *http.Request, name ProblemName) {
	var request GetProblemInfoRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProblemInfo(ctx, request.(GetProblemInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProblemInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProblemInfoResponseObject); ok {
		if err := validResponse.VisitGetProblemInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRanking operation middleware
func (sh *strictHandler) GetRanking(w http.ResponseWriter, r *http.Request, params GetRankingParams) {
	var request GetRankingRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRanking(ctx, request.(GetRankingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRanking")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRankingResponseObject); ok {
		if err := validResponse.VisitGetRankingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSubmissionList operation middleware
func (sh *strictHandler) GetSubmissionList(w http.ResponseWriter, r *http.Request, params GetSubmissionListParams) {
	var request GetSubmissionListRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSubmissionList(ctx, request.(GetSubmissionListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSubmissionList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSubmissionListResponseObject); ok {
		if err := validResponse.VisitGetSubmissionListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSubmissionInfo operation middleware
func (sh *strictHandler) GetSubmissionInfo(w http.ResponseWriter, r *http.Request, id SubmissionId) {
	var request GetSubmissionInfoRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSubmissionInfo(ctx, request.(GetSubmissionInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSubmissionInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSubmissionInfoResponseObject); ok {
		if err := validResponse.VisitGetSubmissionInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostRejudge operation middleware
func (sh *strictHandler) PostRejudge(w http.ResponseWriter, r *http.Request, id SubmissionId) {
	var request PostRejudgeRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostRejudge(ctx, request.(PostRejudgeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostRejudge")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostRejudgeResponseObject); ok {
		if err := validResponse.VisitPostRejudgeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSubmit operation middleware
func (sh *strictHandler) PostSubmit(w http.ResponseWriter, r *http.Request) {
	var request PostSubmitRequestObject

	var body PostSubmitJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostSubmit(ctx, request.(PostSubmitRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSubmit")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostSubmitResponseObject); ok {
		if err := validResponse.VisitPostSubmitResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserInfo operation middleware
func (sh *strictHandler) GetUserInfo(w http.ResponseWriter, r *http.Request, name UserNamePath) {
	var request GetUserInfoRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserInfo(ctx, request.(GetUserInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserInfoResponseObject); ok {
		if err := validResponse.VisitGetUserInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserStatistics operation middleware
func (sh *strictHandler) GetUserStatistics(w http.ResponseWriter, r *http.Request, name UserNamePath) {
	var request GetUserStatisticsRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserStatistics(ctx, request.(GetUserStatisticsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserStatistics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserStatisticsResponseObject); ok {
		if err := validResponse.VisitGetUserStatisticsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xbe2/buhX/KgR3gbW4Suy0Xbf5v9yg27qlt1nSYMCCTGCkY5u1RKoklVuv8He/IKkH",
	"9bSk2EH+amPzcc6P532Of+CAxwlnwJTEix84IYLEoECYv/5Bgs3HUP8vBBkImijKGV6YzxENgSm6pCBO",
	"sYep/jwhao09zEgMeIFpiD0s4FtKBYR4oUQKHpbBGmKij1xyEROl1zH19g32cEwZjdMYL+YeVtsE7Few",
	"AoF3O89cekljqpr0fCLf9U7E0vgBBOJLtCbBRiLFkQCVCoZenZ2czefz1wWp31IQ25LWyBzskhfCkqSR",
	"wouz+dxrIdZeab6eO7SfddJ+s6FJk/RfmyTLDU3QAyy5ABTwKIJAUbZCAmQaKdnFgd7VzkAr+f1YXwn+",
	"EEH8qzm6TnL25X4BMP/0icBPApZ4gf8wK4VwZr+VM5cETdI1YRvKVoMlQNj1SEDARfiCZCFjZJ84tND/",
	"AgTjJn2IqZSUsza7UH777NahvHqwhMhiywuSjpKPfQJSI/8FCMetBKH19Uo/dINy/e2RbYa+glmDscv3",
	"GEd2sSZsBRepEMCUXvWRLfk1fEtBGlEhYUg1mSS6EjwBoShIvFiSSIKHE+ejHziVIIbQYRAp2bizG+8L",
	"4PjDVwgU3nldxMmEMwl7qWseJ4Ao0B7HYbDKQyk6o1XNwwqk8gMiwQ+SpLL/Yav022VbpBKUrao71Hc1",
	"YEcNOIfaVvgmAveEZ23QYAKl2uXV87+m4Qp8nqokVYNA448gHin8to8offXnfK2WehWCECPf5ZlesuDp",
	"vgPDSypVN4YBT5lqldimlJpoSq+lCmI5FsTsPCIE2Ta4sEd7GTldrHx23q/Kht7vK2pDq4KVkCg4MZ+2",
	"4E7DCYoaQ8zFtr7x/btWvKQiKjXkNS4v9c+fREeD1WXEiSqpsB5Zr9RK6LMs6OwXJRM+VCkrmPAciLue",
	"p1vKJvDYpK3t2kvCViOtkqWl8SIdEHn4EURu1QfAl/nafFMXzXWlHEF/RNhquBYagPZpnz2ylVb6IIjY",
	"3oqoGXx8TizF6Pb6Ei25QGoNSIvbHyWK7D6UCL6kEZyiWwmIMARxorbIAqgjrA1AgqhCKZOgTm1kdwls",
	"pYOdN/N5i9p+4owqrv+aiJ8icuN/SyGFfdh9IXLzb71QuyEDIlck8p0gcaDhtPs0NMN21J7H3d5GhOfy",
	"1PaKWd43EqhcIwZnlNosqWiAocmUxK7uIfiCKFhxQUFOfOugOGCwwlSv3u7VHeeK/ZxsR9Kf2N2jqS/e",
	"o0L54Pexy7zy+h7OnhAf6tCFRJHfbWE9LHkqAvDTNgP04bvSuUmEBCxBAAugMEMZ5Uh7L4iBGdvSGnrp",
	"yEv2kqB9nh/lGXDD47Y4sdL7dgE+wq3kj+EgUaGpPKqNIa+Bcs9bPsErTZXUvfo1RAaH1tRQwJmk0iTx",
	"fIki/hsIDReKQCkQ0kMhXVElPcQFSlkIQgZcgKw5prOs5lD87emEW8siXuD/3ZGT/89P/urf//xTm8xl",
	"paqpBq0zXO+PF7UeaMaD4Q+kM7Obctu+d3Ju6Avjr2FFpQIxrVAwxCU5BYsWr9NP09T6wDWYXHT6ATc8",
	"eoTwpkgYajVA8y2yobixcSS3cFo0gel3v8OX518+3Hzxzy+wh88vHFZL6StLYRdEanpNXaqRFBLZbrSC",
	"NQQbEDrnHpTbHixdGpGAD8yMGm5cgpvtZFljxkCb1Dhl294qRUCYL6x8OLw9cB4BYQZUnftnNcXB2tn6",
	"kC0eX2+lEfggBBcHLZKUFFRKJcZL7fdqxS3FFq+CVD/ih6tp1IL5kdgPrm9Uw/Vu8+gcLUJbPSuqx/jE",
	"ZJh10yCsO9PLjWlwrnKNg938cy2Bb7MM3VWWjjS+iSqVfkRUZt+bEh9lWfvT7EVmAf3OzD1f0B2EDavQ",
	"jKsrHa80U2G4zl6Gqov9eHOmprnl/D2dGOn9u3qI1PU8I1Oa0sDUFUF/jgIeAlIcGSuCXsXkOzpDn+gv",
	"rxsx3Lu//OnP7/cSqSLwN4wHm8zl1YW5PVp1rZoBpw/xSYHg0Spq1aLHyCQAWEjZyldEbobWRkTK2Ng9",
	"tgQyfEf9kSpk1kmoHt8G0W3W1xjzXNIP4REi/VmHTbQVszzT7a3plUU5p3A5PSauXu5Vie0C4Ln6QoPa",
	"fSZXKUJom4ZMJE6aY/yYJN0b94QHbizf7GzVI4Pyvk7OKsnbM2SLhxCp7hin2NlsZzP6LbU15J6svZ6r",
	"r7fJGlgtZ6+Z+7e9Gfv5yX9t0n7SnrVrtwNBKqja3mj2LbpLKuCBSDhPbWv+AYgA8bcc6n/+50s+BWBU",
	"3Xxbnr1WKrE9dZoZ2ixMyWvu6MImW+j6w80XdH71Eb0yr0ai107NZ4Hnp2encxO4J8BIQvECvz2dn77F",
	"hse1IXVGUrWeBbar6+f6twIjHFpiiMrGT/DfQdW6v2Z0wOqSOezNfG6Fiymw4kWSJKKBOWP2Vdqi1rDp",
	"gq5GswGm1m74l32INI6JjhE1pShjKROZrEyfEBWsm5xd6Y/beDMhzy883B6Orb7ZiF1VY5RIYXdMiHtH",
	"IXqAziQeL+7qsn53v7t3X8Je0fYYOy+TPZHVWEyYwGWL4F1xndNlq47zLPXi0zO/RKPOdBDw81MN7Bbx",
	"atujS80bTZZjKnp3R2eoquclfYc5w2wxldDFZz4EYQxiOYp7105wuWRWTJjuvEFr7ZScXtw2Fmaex526",
	"ajiZ9n1FDjd6p6kJ1CbR6rWDrHDw6oSGKKs0eIiGHtIZo4dMlvu6pXmiZfBowtIYWxkiI3qDHfg1PqDT",
	"xujDj2X2G2Niz2xhKlMYB7EuNkk1uCIFUiFTKC0Vb/aDhrt92pd52vHa9zHERxe0SXGHwaN0ccVMRhcK",
	"+czHMU1sY65kKDOa+pSsAEVU2gRlFhdTFn1clbMYx+SrZeJjKGclGygkilje3FblHt/4HC5x0pMVPFQ4",
	"mv3Qln83gLFJGlmpxN0fH5lJmpmHCaVyZlP/fahkTdnRiLi/OxgQJFR+b3FUBOtd5qHo5VgZ4Gq9kS7w",
	"qm2Z0RjWpvMHwFj/XUJX/OMUY6f8PObQ4Zj2GRC27XSqyQNjx6GVmfbjQgjT5LYjHt1LTNZnOEA4OrDJ",
	"ZvYdN+LsaC0OVRv3dyOlE3U+3RsmVbvJT1CiY4dMHW3v8Ug5FroO1Mzpl/cVC+yil4tVfSzkQPm+7W0R",
	"B0sHRtUPmo3nj5T/VHuIz5z71Npph8x+CJI8SlUBtBnFHRBsOVXGcSJa+dXXUUV0cuW1VuRzIZlVp836",
	"0Llxp8ZeMkad3aVReMlykCsfq7MSKR5zrk3/D8/w7n73ewAAAP//jKndBUk+AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
