// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	FirebaseAuthScopes = "firebaseAuth.Scopes"
)

// Defines values for SubmissionOrder.
const (
	MinusId  SubmissionOrder = "-id"
	PlusTime SubmissionOrder = "+time"
)

// ChangeCurrentUserInfoRequest defines model for ChangeCurrentUserInfoRequest.
type ChangeCurrentUserInfoRequest struct {
	User User `json:"user"`
}

// ChangeCurrentUserInfoResponse defines model for ChangeCurrentUserInfoResponse.
type ChangeCurrentUserInfoResponse = map[string]interface{}

// CreateHackRequest defines model for CreateHackRequest.
type CreateHackRequest struct {
	Submission  int32   `json:"submission"`
	TestCaseCpp *[]byte `json:"test_case_cpp,omitempty"`
	TestCaseTxt *[]byte `json:"test_case_txt,omitempty"`
}

// CurrentUserInfoResponse defines model for CurrentUserInfoResponse.
type CurrentUserInfoResponse struct {
	User *User `json:"user,omitempty"`
}

// HackInfoResponse defines model for HackInfoResponse.
type HackInfoResponse struct {
	JudgeOutput *[]byte      `json:"judge_output,omitempty"`
	Overview    HackOverview `json:"overview"`
	Stderr      *[]byte      `json:"stderr,omitempty"`
	TestCaseCpp *[]byte      `json:"test_case_cpp,omitempty"`
	TestCaseTxt *[]byte      `json:"test_case_txt,omitempty"`
}

// HackListResponse defines model for HackListResponse.
type HackListResponse struct {
	Count int32          `json:"count"`
	Hacks []HackOverview `json:"hacks"`
}

// HackOverview defines model for HackOverview.
type HackOverview struct {
	HackTime     time.Time `json:"hack_time"`
	Id           int32     `json:"id"`
	Memory       *int64    `json:"memory,omitempty"`
	Status       string    `json:"status"`
	SubmissionId int32     `json:"submission_id"`
	Time         *float32  `json:"time,omitempty"`
	UserName     *string   `json:"user_name,omitempty"`
}

// HackResponse defines model for HackResponse.
type HackResponse struct {
	Id int32 `json:"id"`
}

// Lang defines model for Lang.
type Lang struct {
	Id      string `json:"id"`
	Name    string `json:"name"`
	Version string `json:"version"`
}

// LangListResponse defines model for LangListResponse.
type LangListResponse struct {
	Langs []Lang `json:"langs"`
}

// LibraryUrl Optional URL for the user's library profile. Use an empty string to keep it unset.
type LibraryUrl = string

// Problem defines model for Problem.
type Problem struct {
	// Name Problem identifier consisting of lowercase letters, digits, or underscores.
	Name  ProblemName `json:"name"`
	Title string      `json:"title"`
}

// ProblemCategoriesResponse defines model for ProblemCategoriesResponse.
type ProblemCategoriesResponse struct {
	Categories []ProblemCategory `json:"categories"`
}

// ProblemCategory defines model for ProblemCategory.
type ProblemCategory struct {
	Problems []ProblemName `json:"problems"`
	Title    string        `json:"title"`
}

// ProblemInfoResponse defines model for ProblemInfoResponse.
type ProblemInfoResponse struct {
	OverallVersion string `json:"overall_version"`

	// SourceUrl External reference for the problem statement.
	SourceUrl        string  `json:"source_url"`
	TestcasesVersion string  `json:"testcases_version"`
	TimeLimit        float32 `json:"time_limit"`
	Title            string  `json:"title"`
	Version          string  `json:"version"`
}

// ProblemListResponse defines model for ProblemListResponse.
type ProblemListResponse struct {
	Problems []Problem `json:"problems"`
}

// ProblemName Problem identifier consisting of lowercase letters, digits, or underscores.
type ProblemName = string

// RankingResponse defines model for RankingResponse.
type RankingResponse struct {
	Count      int32            `json:"count"`
	Statistics []UserStatistics `json:"statistics"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Name Unique user identifier consisting of letters, digits, hyphen, or underscore.
	Name Username `json:"name"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse = map[string]interface{}

// SubmissionCaseResult defines model for SubmissionCaseResult.
type SubmissionCaseResult struct {
	Case       string  `json:"case"`
	CheckerOut *[]byte `json:"checker_out,omitempty"`
	Memory     int64   `json:"memory"`
	Status     string  `json:"status"`
	Stderr     *[]byte `json:"stderr,omitempty"`
	Time       float32 `json:"time"`
}

// SubmissionInfoResponse defines model for SubmissionInfoResponse.
type SubmissionInfoResponse struct {
	CanRejudge   bool                    `json:"can_rejudge"`
	CaseResults  *[]SubmissionCaseResult `json:"case_results,omitempty"`
	CompileError *[]byte                 `json:"compile_error,omitempty"`
	Overview     SubmissionOverview      `json:"overview"`
	Source       string                  `json:"source"`
}

// SubmissionListResponse defines model for SubmissionListResponse.
type SubmissionListResponse struct {
	Count       int32                `json:"count"`
	Submissions []SubmissionOverview `json:"submissions"`
}

// SubmissionOrder Sorting order for submissions.
type SubmissionOrder string

// SubmissionOverview defines model for SubmissionOverview.
type SubmissionOverview struct {
	Id             int32      `json:"id"`
	IsLatest       bool       `json:"is_latest"`
	Lang           string     `json:"lang"`
	Memory         int64      `json:"memory"`
	ProblemName    string     `json:"problem_name"`
	ProblemTitle   string     `json:"problem_title"`
	Status         string     `json:"status"`
	SubmissionTime *time.Time `json:"submission_time,omitempty"`
	Time           float32    `json:"time"`
	UserName       *string    `json:"user_name,omitempty"`
}

// SubmitRequest defines model for SubmitRequest.
type SubmitRequest struct {
	Lang string `json:"lang"`

	// Problem Problem identifier consisting of lowercase letters, digits, or underscores.
	Problem ProblemName `json:"problem"`

	// Source Source code to judge (max 1 MiB).
	Source      string `json:"source"`
	TleKnockout *bool  `json:"tle_knockout,omitempty"`
}

// SubmitResponse defines model for SubmitResponse.
type SubmitResponse struct {
	Id int32 `json:"id"`
}

// User defines model for User.
type User struct {
	IsDeveloper bool `json:"is_developer"`

	// LibraryUrl Optional URL for the user's library profile. Use an empty string to keep it unset.
	LibraryUrl LibraryUrl `json:"library_url"`

	// Name Unique user identifier consisting of letters, digits, hyphen, or underscore.
	Name Username `json:"name"`
}

// UserInfoResponse defines model for UserInfoResponse.
type UserInfoResponse struct {
	SolvedMap map[string]string `json:"solved_map"`
	User      User              `json:"user"`
}

// UserStatistics defines model for UserStatistics.
type UserStatistics struct {
	Count int32 `json:"count"`

	// Name Unique user identifier consisting of letters, digits, hyphen, or underscore.
	Name Username `json:"name"`
}

// Username Unique user identifier consisting of letters, digits, hyphen, or underscore.
type Username = string

// HackId defines model for HackId.
type HackId = int32

// HackLimit defines model for HackLimit.
type HackLimit = int32

// HackSkip defines model for HackSkip.
type HackSkip = int32

// RankingLimit defines model for RankingLimit.
type RankingLimit = int32

// RankingSkip defines model for RankingSkip.
type RankingSkip = int32

// SubmissionId defines model for SubmissionId.
type SubmissionId = int32

// SubmissionLimit defines model for SubmissionLimit.
type SubmissionLimit = int32

// SubmissionSkip defines model for SubmissionSkip.
type SubmissionSkip = int32

// UserNamePath Unique user identifier consisting of letters, digits, hyphen, or underscore.
type UserNamePath = Username

// GetHackListParams defines parameters for GetHackList.
type GetHackListParams struct {
	// Skip Number of hacks to skip before collecting results.
	Skip *HackSkip `form:"skip,omitempty" json:"skip,omitempty"`

	// Limit Maximum number of hacks to return (1-1000).
	Limit  *HackLimit `form:"limit,omitempty" json:"limit,omitempty"`
	User   *string    `form:"user,omitempty" json:"user,omitempty"`
	Status *string    `form:"status,omitempty" json:"status,omitempty"`
	Order  *string    `form:"order,omitempty" json:"order,omitempty"`
}

// GetRankingParams defines parameters for GetRanking.
type GetRankingParams struct {
	// Skip Number of ranking records to skip before collecting results.
	Skip *RankingSkip `form:"skip,omitempty" json:"skip,omitempty"`

	// Limit Maximum number of ranking records to return (1-1000).
	Limit *RankingLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSubmissionListParams defines parameters for GetSubmissionList.
type GetSubmissionListParams struct {
	// Skip Number of submissions to skip before collecting results.
	Skip *SubmissionSkip `form:"skip,omitempty" json:"skip,omitempty"`

	// Limit Maximum number of submissions to return (1-1000).
	Limit     *SubmissionLimit `form:"limit,omitempty" json:"limit,omitempty"`
	Problem   *ProblemName     `form:"problem,omitempty" json:"problem,omitempty"`
	Status    *string          `form:"status,omitempty" json:"status,omitempty"`
	Hacked    *bool            `form:"hacked,omitempty" json:"hacked,omitempty"`
	User      *Username        `form:"user,omitempty" json:"user,omitempty"`
	DedupUser *bool            `form:"dedupUser,omitempty" json:"dedupUser,omitempty"`
	Lang      *string          `form:"lang,omitempty" json:"lang,omitempty"`
	Order     *SubmissionOrder `form:"order,omitempty" json:"order,omitempty"`
}

// PatchCurrentUserInfoJSONRequestBody defines body for PatchCurrentUserInfo for application/json ContentType.
type PatchCurrentUserInfoJSONRequestBody = ChangeCurrentUserInfoRequest

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody = RegisterRequest

// PostHackJSONRequestBody defines body for PostHack for application/json ContentType.
type PostHackJSONRequestBody = CreateHackRequest

// PostSubmitJSONRequestBody defines body for PostSubmit for application/json ContentType.
type PostSubmitJSONRequestBody = SubmitRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get current user info
	// (GET /auth/current_user)
	GetCurrentUserInfo(w http.ResponseWriter, r *http.Request)
	// Change current user info
	// (PATCH /auth/current_user)
	PatchCurrentUserInfo(w http.ResponseWriter, r *http.Request)
	// Register user
	// (POST /auth/register)
	PostRegister(w http.ResponseWriter, r *http.Request)
	// Get problem categories
	// (GET /categories)
	GetProblemCategories(w http.ResponseWriter, r *http.Request)
	// List hacks
	// (GET /hacks)
	GetHackList(w http.ResponseWriter, r *http.Request, params GetHackListParams)
	// Submit hack test case
	// (POST /hacks)
	PostHack(w http.ResponseWriter, r *http.Request)
	// Get hack info
	// (GET /hacks/{id})
	GetHackInfo(w http.ResponseWriter, r *http.Request, id HackId)
	// Get language list
	// (GET /langs)
	GetLangList(w http.ResponseWriter, r *http.Request)
	// Get problems
	// (GET /problems)
	GetProblems(w http.ResponseWriter, r *http.Request)
	// Get problem info
	// (GET /problems/{name})
	GetProblemInfo(w http.ResponseWriter, r *http.Request, name ProblemName)
	// Get ranking
	// (GET /ranking)
	GetRanking(w http.ResponseWriter, r *http.Request, params GetRankingParams)
	// Get submissions list
	// (GET /submissions)
	GetSubmissionList(w http.ResponseWriter, r *http.Request, params GetSubmissionListParams)
	// Get submission info
	// (GET /submissions/{id})
	GetSubmissionInfo(w http.ResponseWriter, r *http.Request, id SubmissionId)
	// Submit a solution
	// (POST /submit)
	PostSubmit(w http.ResponseWriter, r *http.Request)
	// Get user info
	// (GET /users/{name})
	GetUserInfo(w http.ResponseWriter, r *http.Request, name UserNamePath)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get current user info
// (GET /auth/current_user)
func (_ Unimplemented) GetCurrentUserInfo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Change current user info
// (PATCH /auth/current_user)
func (_ Unimplemented) PatchCurrentUserInfo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register user
// (POST /auth/register)
func (_ Unimplemented) PostRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get problem categories
// (GET /categories)
func (_ Unimplemented) GetProblemCategories(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List hacks
// (GET /hacks)
func (_ Unimplemented) GetHackList(w http.ResponseWriter, r *http.Request, params GetHackListParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit hack test case
// (POST /hacks)
func (_ Unimplemented) PostHack(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get hack info
// (GET /hacks/{id})
func (_ Unimplemented) GetHackInfo(w http.ResponseWriter, r *http.Request, id HackId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get language list
// (GET /langs)
func (_ Unimplemented) GetLangList(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get problems
// (GET /problems)
func (_ Unimplemented) GetProblems(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get problem info
// (GET /problems/{name})
func (_ Unimplemented) GetProblemInfo(w http.ResponseWriter, r *http.Request, name ProblemName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get ranking
// (GET /ranking)
func (_ Unimplemented) GetRanking(w http.ResponseWriter, r *http.Request, params GetRankingParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get submissions list
// (GET /submissions)
func (_ Unimplemented) GetSubmissionList(w http.ResponseWriter, r *http.Request, params GetSubmissionListParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get submission info
// (GET /submissions/{id})
func (_ Unimplemented) GetSubmissionInfo(w http.ResponseWriter, r *http.Request, id SubmissionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit a solution
// (POST /submit)
func (_ Unimplemented) PostSubmit(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user info
// (GET /users/{name})
func (_ Unimplemented) GetUserInfo(w http.ResponseWriter, r *http.Request, name UserNamePath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCurrentUserInfo operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUserInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUserInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchCurrentUserInfo operation middleware
func (siw *ServerInterfaceWrapper) PatchCurrentUserInfo(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, FirebaseAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchCurrentUserInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRegister operation middleware
func (siw *ServerInterfaceWrapper) PostRegister(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, FirebaseAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProblemCategories operation middleware
func (siw *ServerInterfaceWrapper) GetProblemCategories(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProblemCategories(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHackList operation middleware
func (siw *ServerInterfaceWrapper) GetHackList(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHackListParams

	// ------------- Optional query parameter "skip" -------------

	err = runtime.BindQueryParameter("form", true, false, "skip", r.URL.Query(), &params.Skip)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "skip", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "user" -------------

	err = runtime.BindQueryParameter("form", true, false, "user", r.URL.Query(), &params.User)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHackList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostHack operation middleware
func (siw *ServerInterfaceWrapper) PostHack(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, FirebaseAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostHack(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHackInfo operation middleware
func (siw *ServerInterfaceWrapper) GetHackInfo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id HackId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHackInfo(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLangList operation middleware
func (siw *ServerInterfaceWrapper) GetLangList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLangList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProblems operation middleware
func (siw *ServerInterfaceWrapper) GetProblems(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProblems(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProblemInfo operation middleware
func (siw *ServerInterfaceWrapper) GetProblemInfo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name ProblemName

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProblemInfo(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRanking operation middleware
func (siw *ServerInterfaceWrapper) GetRanking(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRankingParams

	// ------------- Optional query parameter "skip" -------------

	err = runtime.BindQueryParameter("form", true, false, "skip", r.URL.Query(), &params.Skip)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "skip", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRanking(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubmissionList operation middleware
func (siw *ServerInterfaceWrapper) GetSubmissionList(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSubmissionListParams

	// ------------- Optional query parameter "skip" -------------

	err = runtime.BindQueryParameter("form", true, false, "skip", r.URL.Query(), &params.Skip)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "skip", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "problem" -------------

	err = runtime.BindQueryParameter("form", true, false, "problem", r.URL.Query(), &params.Problem)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "problem", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "hacked" -------------

	err = runtime.BindQueryParameter("form", true, false, "hacked", r.URL.Query(), &params.Hacked)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hacked", Err: err})
		return
	}

	// ------------- Optional query parameter "user" -------------

	err = runtime.BindQueryParameter("form", true, false, "user", r.URL.Query(), &params.User)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user", Err: err})
		return
	}

	// ------------- Optional query parameter "dedupUser" -------------

	err = runtime.BindQueryParameter("form", true, false, "dedupUser", r.URL.Query(), &params.DedupUser)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dedupUser", Err: err})
		return
	}

	// ------------- Optional query parameter "lang" -------------

	err = runtime.BindQueryParameter("form", true, false, "lang", r.URL.Query(), &params.Lang)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lang", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubmissionList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubmissionInfo operation middleware
func (siw *ServerInterfaceWrapper) GetSubmissionInfo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id SubmissionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubmissionInfo(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSubmit operation middleware
func (siw *ServerInterfaceWrapper) PostSubmit(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, FirebaseAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSubmit(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserInfo operation middleware
func (siw *ServerInterfaceWrapper) GetUserInfo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name UserNamePath

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserInfo(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/current_user", wrapper.GetCurrentUserInfo)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/auth/current_user", wrapper.PatchCurrentUserInfo)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.PostRegister)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/categories", wrapper.GetProblemCategories)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/hacks", wrapper.GetHackList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/hacks", wrapper.PostHack)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/hacks/{id}", wrapper.GetHackInfo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/langs", wrapper.GetLangList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/problems", wrapper.GetProblems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/problems/{name}", wrapper.GetProblemInfo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ranking", wrapper.GetRanking)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/submissions", wrapper.GetSubmissionList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/submissions/{id}", wrapper.GetSubmissionInfo)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/submit", wrapper.PostSubmit)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{name}", wrapper.GetUserInfo)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xbe2/cuBH/KgR7QBOc7F0nadrufz4jbdPzJYYd44AarsCVZncZS6RCUr5sjf3uBUm9",
	"RWkledfIX3fW8jHzm/cM84QDHiecAVMSL55wQgSJQYEwf/2LBA8fQ/1/IchA0ERRzvDCfEc0BKboioI4",
	"xR6m+ntC1AZ7mJEY8ALTEHtYwLeUCgjxQokUPCyDDcREH7niIiZKr2Pq7Rvs4ZgyGqcxXsw9rLYJ2J9g",
	"DQLvdp659JLGVLXp+Y181zsRS+MlCMRXaEOCB4kURwJUKhh6dXZyNp/PXxekfktBbEtaI3NwlbwQViSN",
	"FF6czeeeg1h7pfl5XqH9rJP2mweatEn/1CZZPtAELWHFBaCARxEEirI1EiDTSMkuDvQuNwNO8vuxvhJ8",
	"GUH8yRzdJDn7cb8CmP/0qcBPAlZ4gf80K5VwZn+VsyoJmqRrwh4oWw/WAGHXIwEBF+EPpAsZI/vUwUH/",
	"D6AYN+kyplJSzlx+ofz1xb1DefVgDZHFlh9IO0o+9ilIg/wfQDluJQhtr1da0C3K9a9H9hn6CmYdxi7f",
	"YwLZxYawNVykQgBTetVHtuLX8C0FaVSFhCHVZJLoSvAEhKIg8WJFIgkeTiqfnnAqQQyhwyBSsnFnN94X",
	"wPHlVwgU3nldxMmEMwl7qWsfJ4Ao0BGnwmCdh1J1RpuahxVI5QdEgh8kSW3/cqu07LItUgnK1vUd6rsa",
	"sKMBXIVaJ3wTgXuGWFs0mESpcXn9/K9puAafpypJ1SDQ+COIRwp/7CNKX/05X6u1XoUgxEi5vJAkC57u",
	"OzC8pFJ1YxjwlCmnxra11GRTei1VEMuxIGbnESHItsWFPdrLyOli5XNFfnU29H5fUZtaFayERMGJ+erA",
	"nYYTDDWGmIttc+P7d068pCIqNeS1Li/tz59ER4vVVcSJKqmwEVmv1Ebosyzp7Fclkz7UKSuY8CoQd4mn",
	"W8sm8NimzXXtJWHrkV7J0tKSSAdEHn4EkXv1AfBlsTbf1EVz0yhH0B8Rth5uhQagfdZnj3TSSpeCiO2t",
	"iNrJx+fEUoxury/RigukNoC0uv1ZosjuQ4ngKxrBKbqVgAhDECdqiyyAOsN6AEgQVShlEtSpzewuga11",
	"svNmPneYbVbDjAQtl+7g6kibmIoGGE0mcLvaBWF27AVRsOaCgpwo96A4YLDw61dv9+pB5Yr9nGxH0p/Y",
	"3aOpL+RRo3ywfOwyr7y+h7Nn5Do6DJMo8ru9hYclT0UAfuoypg/flc6zIyRgBQJYAIVJZZQj7YkhBmbs",
	"xJlG6CxC9pKg/bcf5dVcK3o4HHIZSboAH+Eic2FUkKjRVB7lYshrodwjy2d42Kmaute+hujg0P4QCjiT",
	"VJqClK9QxP8AoeFCESgFQnoopGuqpIe4QCkLQciAC5ANJ3uW1c/F354uHrUu4gX+7x05+d/85O/+/c8/",
	"uXQua7tMdWidqWd/7qPtQDMeDBeQrjJuym375FS5oS8lvYY1lQrEtKJ3SEiqFN+OqNNP09Rat+yWXBAJ",
	"16bX4agbiHT7gmADwQMIXZYNKn8OllGPqNEGJs+t6CihmhBnhUXGwH0vlP2FbECYL8CUsxXelpxHQJgB",
	"VZeHWdtpsNI7BekIpHorjcAHIbg4aB1dUlCrpo3z3x8siluKLV4NqX7ED1f2VpqCE7AfXAJXr+nzOpWj",
	"RWgbLEWDEZ+YIqTRQebCRgm93GQVlat0OACmfe1dtvnnRo1Xit3B1NBKr40qlX5EVOY22xofZYXd8/xF",
	"FnD9zuIuX9Cd2wwr4se1Ho5XvdcYbrKXoVrFfrw7U9OiXS7PSurx/l0z8+gSz8hKoXQwTUPQ31HAQ9C1",
	"p/Ei6FVMvqMz9Bv95XUrNXr3t7/89f1eIlUE/gPjwUMW8prK7E4Cq17NgNOH+KT86mhNl9usrzuGFumH",
	"8AiR/tZh8LZjkFdHvT2NsilRadxMz6Pql3t1YrsAeEatKHn0CKEfk6R7Y6vZwkCn+beffv30+fdPs8vz",
	"Lx9uvvjnF7PzC6eHaZL8vBGLV6W5C5GbWl7+AoXAISTfHWeLne2pG6PfUtvq6inImmXYZptsgDXKsYbL",
	"edtbjJ2f/MfWYyfugky7PghSQdX2RrNv0V1RAUsi4Ty1E8QlEAHiHznU//79Sz6sNBZpfi3P3iiV2NEf",
	"ZStuTNeGyrw1iC5swo+uP9x8QedXH9ErIzUSva6U8ws8Pz07nZvkMQFGEooX+O3p/PQtNjxuDKkzkqrN",
	"LLDDJz9X2TUY5dAaQ1Q2Jcf/BNUYUpkJp7VHc9ib+dwqF1Ng1YskSUQDc8bsq7T9imFD0K55mAGmYai/",
	"WkGkcUx0nqIpRRlLmcpoYneG7WDT5uxKf3bxZsLuLzzcHo6tvhHurm4xSqSwOybEvRPbHqAzjceLu6au",
	"393v7quSsFe4hLHzMt0TWflsElsuHYp3xXVdka06jliafYUXlkSrhXAQ8PNTDewW8XpHu8vMW/3zYxp6",
	"d7N+qKnn3doKc4bZYnjaxWc+qzUOsXwxeOcmuFwyKx7C7bxBa+1jHr3Y9Xolj/cFXK0g495X1BGjd5q6",
	"tPFgplm/ZsXrqxMaoqza9RANPaSrFg+ZSuu1oy+udfBoytKarg/REb3Bvks0MaDTx+jDj+X2W69ZXtjD",
	"1IbFB/EutlAyuCJd2CLTrCsNb/ZEw90+68si7Xjr+xjioyvapLzD4FGGuGJ03IVCPpo+pottjb+HMqOp",
	"T8kaUESNynp4Vp3U7IkfLxE2JrFV8FDjaPakveNuAGOTtLbWMbk/PjKTtDcPpaUCZw94+1DJZlKjEak+",
	"IR4QSGtPp4+KYHPINhS9HCsDXKOH3QVevX0+GsPGQ9sBMDafGHflCJWm2ZSX7odOWbRfhdC1s9L1G5hf",
	"De1euI8LIUyT246cbS8xWT/4ACnbwGGI2XfcrKxjBDTUbKpPwMtAU/m6N5WoT/2eYUTHTis6xpPjkap4",
	"aPNR9ZfPNlk7UnJbH1K8cGLb6NcfMrUlSPIoNacYoLUfGZIlVFpI4/Sw9i8PjqqHk9tq1Q6OAVU85syZ",
	"MQKe4d397v8BAAD//80Yfl2QNwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
