// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/library_checker.proto

package librarychecker

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoginRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsAdmin              bool     `protobuf:"varint,2,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type UserInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoRequest) Reset()         { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()    {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{5}
}

func (m *UserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRequest.Unmarshal(m, b)
}
func (m *UserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRequest.Marshal(b, m, deterministic)
}
func (m *UserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRequest.Merge(m, src)
}
func (m *UserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoRequest.Size(m)
}
func (m *UserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRequest proto.InternalMessageInfo

type UserInfoResponse struct {
	IsAdmin              bool     `protobuf:"varint,1,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{6}
}

func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (m *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(m, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *UserInfoResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListRequest) Reset()         { *m = UserListRequest{} }
func (m *UserListRequest) String() string { return proto.CompactTextString(m) }
func (*UserListRequest) ProtoMessage()    {}
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{7}
}

func (m *UserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRequest.Unmarshal(m, b)
}
func (m *UserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRequest.Marshal(b, m, deterministic)
}
func (m *UserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRequest.Merge(m, src)
}
func (m *UserListRequest) XXX_Size() int {
	return xxx_messageInfo_UserListRequest.Size(m)
}
func (m *UserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRequest proto.InternalMessageInfo

type UserListResponse struct {
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListResponse) Reset()         { *m = UserListResponse{} }
func (m *UserListResponse) String() string { return proto.CompactTextString(m) }
func (*UserListResponse) ProtoMessage()    {}
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{8}
}

func (m *UserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse.Unmarshal(m, b)
}
func (m *UserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse.Marshal(b, m, deterministic)
}
func (m *UserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse.Merge(m, src)
}
func (m *UserListResponse) XXX_Size() int {
	return xxx_messageInfo_UserListResponse.Size(m)
}
func (m *UserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse proto.InternalMessageInfo

func (m *UserListResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type Problem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Problem) Reset()         { *m = Problem{} }
func (m *Problem) String() string { return proto.CompactTextString(m) }
func (*Problem) ProtoMessage()    {}
func (*Problem) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{9}
}

func (m *Problem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Problem.Unmarshal(m, b)
}
func (m *Problem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Problem.Marshal(b, m, deterministic)
}
func (m *Problem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Problem.Merge(m, src)
}
func (m *Problem) XXX_Size() int {
	return xxx_messageInfo_Problem.Size(m)
}
func (m *Problem) XXX_DiscardUnknown() {
	xxx_messageInfo_Problem.DiscardUnknown(m)
}

var xxx_messageInfo_Problem proto.InternalMessageInfo

func (m *Problem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Problem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type ProblemListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProblemListRequest) Reset()         { *m = ProblemListRequest{} }
func (m *ProblemListRequest) String() string { return proto.CompactTextString(m) }
func (*ProblemListRequest) ProtoMessage()    {}
func (*ProblemListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{10}
}

func (m *ProblemListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemListRequest.Unmarshal(m, b)
}
func (m *ProblemListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemListRequest.Marshal(b, m, deterministic)
}
func (m *ProblemListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemListRequest.Merge(m, src)
}
func (m *ProblemListRequest) XXX_Size() int {
	return xxx_messageInfo_ProblemListRequest.Size(m)
}
func (m *ProblemListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemListRequest proto.InternalMessageInfo

type ProblemListResponse struct {
	Problems             []*Problem `protobuf:"bytes,1,rep,name=problems,proto3" json:"problems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProblemListResponse) Reset()         { *m = ProblemListResponse{} }
func (m *ProblemListResponse) String() string { return proto.CompactTextString(m) }
func (*ProblemListResponse) ProtoMessage()    {}
func (*ProblemListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{11}
}

func (m *ProblemListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemListResponse.Unmarshal(m, b)
}
func (m *ProblemListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemListResponse.Marshal(b, m, deterministic)
}
func (m *ProblemListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemListResponse.Merge(m, src)
}
func (m *ProblemListResponse) XXX_Size() int {
	return xxx_messageInfo_ProblemListResponse.Size(m)
}
func (m *ProblemListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemListResponse proto.InternalMessageInfo

func (m *ProblemListResponse) GetProblems() []*Problem {
	if m != nil {
		return m.Problems
	}
	return nil
}

type ProblemInfoRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProblemInfoRequest) Reset()         { *m = ProblemInfoRequest{} }
func (m *ProblemInfoRequest) String() string { return proto.CompactTextString(m) }
func (*ProblemInfoRequest) ProtoMessage()    {}
func (*ProblemInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{12}
}

func (m *ProblemInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemInfoRequest.Unmarshal(m, b)
}
func (m *ProblemInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemInfoRequest.Marshal(b, m, deterministic)
}
func (m *ProblemInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemInfoRequest.Merge(m, src)
}
func (m *ProblemInfoRequest) XXX_Size() int {
	return xxx_messageInfo_ProblemInfoRequest.Size(m)
}
func (m *ProblemInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemInfoRequest proto.InternalMessageInfo

func (m *ProblemInfoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ProblemInfoResponse struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Statement            string   `protobuf:"bytes,2,opt,name=statement,proto3" json:"statement,omitempty"`
	TimeLimit            float64  `protobuf:"fixed64,3,opt,name=time_limit,json=timeLimit,proto3" json:"time_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProblemInfoResponse) Reset()         { *m = ProblemInfoResponse{} }
func (m *ProblemInfoResponse) String() string { return proto.CompactTextString(m) }
func (*ProblemInfoResponse) ProtoMessage()    {}
func (*ProblemInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{13}
}

func (m *ProblemInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemInfoResponse.Unmarshal(m, b)
}
func (m *ProblemInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemInfoResponse.Marshal(b, m, deterministic)
}
func (m *ProblemInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemInfoResponse.Merge(m, src)
}
func (m *ProblemInfoResponse) XXX_Size() int {
	return xxx_messageInfo_ProblemInfoResponse.Size(m)
}
func (m *ProblemInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemInfoResponse proto.InternalMessageInfo

func (m *ProblemInfoResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ProblemInfoResponse) GetStatement() string {
	if m != nil {
		return m.Statement
	}
	return ""
}

func (m *ProblemInfoResponse) GetTimeLimit() float64 {
	if m != nil {
		return m.TimeLimit
	}
	return 0
}

type SubmitRequest struct {
	Problem              string   `protobuf:"bytes,1,opt,name=problem,proto3" json:"problem,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Lang                 string   `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitRequest) Reset()         { *m = SubmitRequest{} }
func (m *SubmitRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitRequest) ProtoMessage()    {}
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{14}
}

func (m *SubmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitRequest.Unmarshal(m, b)
}
func (m *SubmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitRequest.Marshal(b, m, deterministic)
}
func (m *SubmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitRequest.Merge(m, src)
}
func (m *SubmitRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitRequest.Size(m)
}
func (m *SubmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitRequest proto.InternalMessageInfo

func (m *SubmitRequest) GetProblem() string {
	if m != nil {
		return m.Problem
	}
	return ""
}

func (m *SubmitRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SubmitRequest) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

type SubmitResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitResponse) Reset()         { *m = SubmitResponse{} }
func (m *SubmitResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitResponse) ProtoMessage()    {}
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{15}
}

func (m *SubmitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitResponse.Unmarshal(m, b)
}
func (m *SubmitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitResponse.Marshal(b, m, deterministic)
}
func (m *SubmitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitResponse.Merge(m, src)
}
func (m *SubmitResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitResponse.Size(m)
}
func (m *SubmitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitResponse proto.InternalMessageInfo

func (m *SubmitResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SubmissionOverview struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProblemName          string   `protobuf:"bytes,2,opt,name=problem_name,json=problemName,proto3" json:"problem_name,omitempty"`
	ProblemTitle         string   `protobuf:"bytes,3,opt,name=problem_title,json=problemTitle,proto3" json:"problem_title,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Lang                 string   `protobuf:"bytes,5,opt,name=lang,proto3" json:"lang,omitempty"`
	IsLatest             bool     `protobuf:"varint,6,opt,name=is_latest,json=isLatest,proto3" json:"is_latest,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Time                 float64  `protobuf:"fixed64,8,opt,name=time,proto3" json:"time,omitempty"`
	Memory               int64    `protobuf:"varint,9,opt,name=memory,proto3" json:"memory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmissionOverview) Reset()         { *m = SubmissionOverview{} }
func (m *SubmissionOverview) String() string { return proto.CompactTextString(m) }
func (*SubmissionOverview) ProtoMessage()    {}
func (*SubmissionOverview) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{16}
}

func (m *SubmissionOverview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionOverview.Unmarshal(m, b)
}
func (m *SubmissionOverview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionOverview.Marshal(b, m, deterministic)
}
func (m *SubmissionOverview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionOverview.Merge(m, src)
}
func (m *SubmissionOverview) XXX_Size() int {
	return xxx_messageInfo_SubmissionOverview.Size(m)
}
func (m *SubmissionOverview) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionOverview.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionOverview proto.InternalMessageInfo

func (m *SubmissionOverview) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SubmissionOverview) GetProblemName() string {
	if m != nil {
		return m.ProblemName
	}
	return ""
}

func (m *SubmissionOverview) GetProblemTitle() string {
	if m != nil {
		return m.ProblemTitle
	}
	return ""
}

func (m *SubmissionOverview) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SubmissionOverview) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *SubmissionOverview) GetIsLatest() bool {
	if m != nil {
		return m.IsLatest
	}
	return false
}

func (m *SubmissionOverview) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SubmissionOverview) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *SubmissionOverview) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

type SubmissionCaseResult struct {
	Case                 string   `protobuf:"bytes,1,opt,name=case,proto3" json:"case,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Time                 float64  `protobuf:"fixed64,3,opt,name=time,proto3" json:"time,omitempty"`
	Memory               int64    `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmissionCaseResult) Reset()         { *m = SubmissionCaseResult{} }
func (m *SubmissionCaseResult) String() string { return proto.CompactTextString(m) }
func (*SubmissionCaseResult) ProtoMessage()    {}
func (*SubmissionCaseResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{17}
}

func (m *SubmissionCaseResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionCaseResult.Unmarshal(m, b)
}
func (m *SubmissionCaseResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionCaseResult.Marshal(b, m, deterministic)
}
func (m *SubmissionCaseResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionCaseResult.Merge(m, src)
}
func (m *SubmissionCaseResult) XXX_Size() int {
	return xxx_messageInfo_SubmissionCaseResult.Size(m)
}
func (m *SubmissionCaseResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionCaseResult.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionCaseResult proto.InternalMessageInfo

func (m *SubmissionCaseResult) GetCase() string {
	if m != nil {
		return m.Case
	}
	return ""
}

func (m *SubmissionCaseResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SubmissionCaseResult) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *SubmissionCaseResult) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

type SubmissionInfoRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmissionInfoRequest) Reset()         { *m = SubmissionInfoRequest{} }
func (m *SubmissionInfoRequest) String() string { return proto.CompactTextString(m) }
func (*SubmissionInfoRequest) ProtoMessage()    {}
func (*SubmissionInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{18}
}

func (m *SubmissionInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionInfoRequest.Unmarshal(m, b)
}
func (m *SubmissionInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionInfoRequest.Marshal(b, m, deterministic)
}
func (m *SubmissionInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionInfoRequest.Merge(m, src)
}
func (m *SubmissionInfoRequest) XXX_Size() int {
	return xxx_messageInfo_SubmissionInfoRequest.Size(m)
}
func (m *SubmissionInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionInfoRequest proto.InternalMessageInfo

func (m *SubmissionInfoRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SubmissionInfoResponse struct {
	Overview             *SubmissionOverview     `protobuf:"bytes,1,opt,name=overview,proto3" json:"overview,omitempty"`
	CaseResults          []*SubmissionCaseResult `protobuf:"bytes,2,rep,name=case_results,json=caseResults,proto3" json:"case_results,omitempty"`
	Source               string                  `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	CanRejudge           bool                    `protobuf:"varint,4,opt,name=can_rejudge,json=canRejudge,proto3" json:"can_rejudge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SubmissionInfoResponse) Reset()         { *m = SubmissionInfoResponse{} }
func (m *SubmissionInfoResponse) String() string { return proto.CompactTextString(m) }
func (*SubmissionInfoResponse) ProtoMessage()    {}
func (*SubmissionInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{19}
}

func (m *SubmissionInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionInfoResponse.Unmarshal(m, b)
}
func (m *SubmissionInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionInfoResponse.Marshal(b, m, deterministic)
}
func (m *SubmissionInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionInfoResponse.Merge(m, src)
}
func (m *SubmissionInfoResponse) XXX_Size() int {
	return xxx_messageInfo_SubmissionInfoResponse.Size(m)
}
func (m *SubmissionInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionInfoResponse proto.InternalMessageInfo

func (m *SubmissionInfoResponse) GetOverview() *SubmissionOverview {
	if m != nil {
		return m.Overview
	}
	return nil
}

func (m *SubmissionInfoResponse) GetCaseResults() []*SubmissionCaseResult {
	if m != nil {
		return m.CaseResults
	}
	return nil
}

func (m *SubmissionInfoResponse) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SubmissionInfoResponse) GetCanRejudge() bool {
	if m != nil {
		return m.CanRejudge
	}
	return false
}

type SubmissionListRequest struct {
	Skip                 uint32   `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Problem              string   `protobuf:"bytes,3,opt,name=problem,proto3" json:"problem,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	User                 string   `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Order                string   `protobuf:"bytes,6,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmissionListRequest) Reset()         { *m = SubmissionListRequest{} }
func (m *SubmissionListRequest) String() string { return proto.CompactTextString(m) }
func (*SubmissionListRequest) ProtoMessage()    {}
func (*SubmissionListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{20}
}

func (m *SubmissionListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionListRequest.Unmarshal(m, b)
}
func (m *SubmissionListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionListRequest.Marshal(b, m, deterministic)
}
func (m *SubmissionListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionListRequest.Merge(m, src)
}
func (m *SubmissionListRequest) XXX_Size() int {
	return xxx_messageInfo_SubmissionListRequest.Size(m)
}
func (m *SubmissionListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionListRequest proto.InternalMessageInfo

func (m *SubmissionListRequest) GetSkip() uint32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *SubmissionListRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SubmissionListRequest) GetProblem() string {
	if m != nil {
		return m.Problem
	}
	return ""
}

func (m *SubmissionListRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SubmissionListRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *SubmissionListRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

type SubmissionListResponse struct {
	Submissions          []*SubmissionOverview `protobuf:"bytes,1,rep,name=submissions,proto3" json:"submissions,omitempty"`
	Count                int32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SubmissionListResponse) Reset()         { *m = SubmissionListResponse{} }
func (m *SubmissionListResponse) String() string { return proto.CompactTextString(m) }
func (*SubmissionListResponse) ProtoMessage()    {}
func (*SubmissionListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{21}
}

func (m *SubmissionListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionListResponse.Unmarshal(m, b)
}
func (m *SubmissionListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionListResponse.Marshal(b, m, deterministic)
}
func (m *SubmissionListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionListResponse.Merge(m, src)
}
func (m *SubmissionListResponse) XXX_Size() int {
	return xxx_messageInfo_SubmissionListResponse.Size(m)
}
func (m *SubmissionListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionListResponse proto.InternalMessageInfo

func (m *SubmissionListResponse) GetSubmissions() []*SubmissionOverview {
	if m != nil {
		return m.Submissions
	}
	return nil
}

func (m *SubmissionListResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type RejudgeRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejudgeRequest) Reset()         { *m = RejudgeRequest{} }
func (m *RejudgeRequest) String() string { return proto.CompactTextString(m) }
func (*RejudgeRequest) ProtoMessage()    {}
func (*RejudgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{22}
}

func (m *RejudgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejudgeRequest.Unmarshal(m, b)
}
func (m *RejudgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejudgeRequest.Marshal(b, m, deterministic)
}
func (m *RejudgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejudgeRequest.Merge(m, src)
}
func (m *RejudgeRequest) XXX_Size() int {
	return xxx_messageInfo_RejudgeRequest.Size(m)
}
func (m *RejudgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RejudgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RejudgeRequest proto.InternalMessageInfo

func (m *RejudgeRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RejudgeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejudgeResponse) Reset()         { *m = RejudgeResponse{} }
func (m *RejudgeResponse) String() string { return proto.CompactTextString(m) }
func (*RejudgeResponse) ProtoMessage()    {}
func (*RejudgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{23}
}

func (m *RejudgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejudgeResponse.Unmarshal(m, b)
}
func (m *RejudgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejudgeResponse.Marshal(b, m, deterministic)
}
func (m *RejudgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejudgeResponse.Merge(m, src)
}
func (m *RejudgeResponse) XXX_Size() int {
	return xxx_messageInfo_RejudgeResponse.Size(m)
}
func (m *RejudgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RejudgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RejudgeResponse proto.InternalMessageInfo

type Lang struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lang) Reset()         { *m = Lang{} }
func (m *Lang) String() string { return proto.CompactTextString(m) }
func (*Lang) ProtoMessage()    {}
func (*Lang) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{24}
}

func (m *Lang) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lang.Unmarshal(m, b)
}
func (m *Lang) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lang.Marshal(b, m, deterministic)
}
func (m *Lang) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lang.Merge(m, src)
}
func (m *Lang) XXX_Size() int {
	return xxx_messageInfo_Lang.Size(m)
}
func (m *Lang) XXX_DiscardUnknown() {
	xxx_messageInfo_Lang.DiscardUnknown(m)
}

var xxx_messageInfo_Lang proto.InternalMessageInfo

func (m *Lang) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Lang) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Lang) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LangListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LangListRequest) Reset()         { *m = LangListRequest{} }
func (m *LangListRequest) String() string { return proto.CompactTextString(m) }
func (*LangListRequest) ProtoMessage()    {}
func (*LangListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{25}
}

func (m *LangListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LangListRequest.Unmarshal(m, b)
}
func (m *LangListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LangListRequest.Marshal(b, m, deterministic)
}
func (m *LangListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LangListRequest.Merge(m, src)
}
func (m *LangListRequest) XXX_Size() int {
	return xxx_messageInfo_LangListRequest.Size(m)
}
func (m *LangListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LangListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LangListRequest proto.InternalMessageInfo

type LangListResponse struct {
	Langs                []*Lang  `protobuf:"bytes,1,rep,name=langs,proto3" json:"langs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LangListResponse) Reset()         { *m = LangListResponse{} }
func (m *LangListResponse) String() string { return proto.CompactTextString(m) }
func (*LangListResponse) ProtoMessage()    {}
func (*LangListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{26}
}

func (m *LangListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LangListResponse.Unmarshal(m, b)
}
func (m *LangListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LangListResponse.Marshal(b, m, deterministic)
}
func (m *LangListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LangListResponse.Merge(m, src)
}
func (m *LangListResponse) XXX_Size() int {
	return xxx_messageInfo_LangListResponse.Size(m)
}
func (m *LangListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LangListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LangListResponse proto.InternalMessageInfo

func (m *LangListResponse) GetLangs() []*Lang {
	if m != nil {
		return m.Langs
	}
	return nil
}

type UserStatistics struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserStatistics) Reset()         { *m = UserStatistics{} }
func (m *UserStatistics) String() string { return proto.CompactTextString(m) }
func (*UserStatistics) ProtoMessage()    {}
func (*UserStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{27}
}

func (m *UserStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStatistics.Unmarshal(m, b)
}
func (m *UserStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStatistics.Marshal(b, m, deterministic)
}
func (m *UserStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStatistics.Merge(m, src)
}
func (m *UserStatistics) XXX_Size() int {
	return xxx_messageInfo_UserStatistics.Size(m)
}
func (m *UserStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_UserStatistics proto.InternalMessageInfo

func (m *UserStatistics) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserStatistics) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type RankingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RankingRequest) Reset()         { *m = RankingRequest{} }
func (m *RankingRequest) String() string { return proto.CompactTextString(m) }
func (*RankingRequest) ProtoMessage()    {}
func (*RankingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{28}
}

func (m *RankingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankingRequest.Unmarshal(m, b)
}
func (m *RankingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankingRequest.Marshal(b, m, deterministic)
}
func (m *RankingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankingRequest.Merge(m, src)
}
func (m *RankingRequest) XXX_Size() int {
	return xxx_messageInfo_RankingRequest.Size(m)
}
func (m *RankingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RankingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RankingRequest proto.InternalMessageInfo

type RankingResponse struct {
	Statistics           []*UserStatistics `protobuf:"bytes,1,rep,name=statistics,proto3" json:"statistics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RankingResponse) Reset()         { *m = RankingResponse{} }
func (m *RankingResponse) String() string { return proto.CompactTextString(m) }
func (*RankingResponse) ProtoMessage()    {}
func (*RankingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{29}
}

func (m *RankingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankingResponse.Unmarshal(m, b)
}
func (m *RankingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankingResponse.Marshal(b, m, deterministic)
}
func (m *RankingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankingResponse.Merge(m, src)
}
func (m *RankingResponse) XXX_Size() int {
	return xxx_messageInfo_RankingResponse.Size(m)
}
func (m *RankingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RankingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RankingResponse proto.InternalMessageInfo

func (m *RankingResponse) GetStatistics() []*UserStatistics {
	if m != nil {
		return m.Statistics
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "librarychecker.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "librarychecker.RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "librarychecker.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "librarychecker.LoginResponse")
	proto.RegisterType((*User)(nil), "librarychecker.User")
	proto.RegisterType((*UserInfoRequest)(nil), "librarychecker.UserInfoRequest")
	proto.RegisterType((*UserInfoResponse)(nil), "librarychecker.UserInfoResponse")
	proto.RegisterType((*UserListRequest)(nil), "librarychecker.UserListRequest")
	proto.RegisterType((*UserListResponse)(nil), "librarychecker.UserListResponse")
	proto.RegisterType((*Problem)(nil), "librarychecker.Problem")
	proto.RegisterType((*ProblemListRequest)(nil), "librarychecker.ProblemListRequest")
	proto.RegisterType((*ProblemListResponse)(nil), "librarychecker.ProblemListResponse")
	proto.RegisterType((*ProblemInfoRequest)(nil), "librarychecker.ProblemInfoRequest")
	proto.RegisterType((*ProblemInfoResponse)(nil), "librarychecker.ProblemInfoResponse")
	proto.RegisterType((*SubmitRequest)(nil), "librarychecker.SubmitRequest")
	proto.RegisterType((*SubmitResponse)(nil), "librarychecker.SubmitResponse")
	proto.RegisterType((*SubmissionOverview)(nil), "librarychecker.SubmissionOverview")
	proto.RegisterType((*SubmissionCaseResult)(nil), "librarychecker.SubmissionCaseResult")
	proto.RegisterType((*SubmissionInfoRequest)(nil), "librarychecker.SubmissionInfoRequest")
	proto.RegisterType((*SubmissionInfoResponse)(nil), "librarychecker.SubmissionInfoResponse")
	proto.RegisterType((*SubmissionListRequest)(nil), "librarychecker.SubmissionListRequest")
	proto.RegisterType((*SubmissionListResponse)(nil), "librarychecker.SubmissionListResponse")
	proto.RegisterType((*RejudgeRequest)(nil), "librarychecker.RejudgeRequest")
	proto.RegisterType((*RejudgeResponse)(nil), "librarychecker.RejudgeResponse")
	proto.RegisterType((*Lang)(nil), "librarychecker.Lang")
	proto.RegisterType((*LangListRequest)(nil), "librarychecker.LangListRequest")
	proto.RegisterType((*LangListResponse)(nil), "librarychecker.LangListResponse")
	proto.RegisterType((*UserStatistics)(nil), "librarychecker.UserStatistics")
	proto.RegisterType((*RankingRequest)(nil), "librarychecker.RankingRequest")
	proto.RegisterType((*RankingResponse)(nil), "librarychecker.RankingResponse")
}

func init() {
	proto.RegisterFile("proto/library_checker.proto", fileDescriptor_9accbd90656ef5bc)
}

var fileDescriptor_9accbd90656ef5bc = []byte{
	// 1042 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x57, 0xcd, 0x6e, 0x1b, 0x37,
	0x10, 0x8e, 0xfe, 0xa5, 0x91, 0xed, 0x38, 0xac, 0x93, 0xaa, 0x4e, 0xfc, 0x53, 0xba, 0x49, 0x8d,
	0x1e, 0x5c, 0xc0, 0x46, 0x2f, 0x3d, 0x18, 0x08, 0x12, 0xb4, 0x48, 0x21, 0x34, 0x2d, 0xdd, 0xa0,
	0xbd, 0x09, 0x6b, 0x99, 0x75, 0xb6, 0x96, 0x76, 0xdd, 0xe5, 0x2a, 0x41, 0xee, 0x7d, 0x8d, 0xbe,
	0x58, 0x1f, 0xa6, 0x28, 0x87, 0x1c, 0xee, 0x72, 0xff, 0xe4, 0x22, 0x37, 0xce, 0x68, 0xf8, 0xcd,
	0xc7, 0x8f, 0x33, 0xc3, 0x15, 0x3c, 0xbe, 0x4d, 0xe2, 0x34, 0xfe, 0x7a, 0x11, 0x5e, 0x26, 0x41,
	0xf2, 0x61, 0x36, 0x7f, 0x2b, 0xe7, 0x37, 0x32, 0x39, 0x31, 0x5e, 0xb6, 0x45, 0x6e, 0xf2, 0xf2,
	0xe7, 0x70, 0x5f, 0xc8, 0xeb, 0x50, 0xa5, 0x32, 0x11, 0xf2, 0xcf, 0x95, 0x54, 0x29, 0x63, 0xd0,
	0x8d, 0x82, 0xa5, 0x9c, 0xb4, 0x0e, 0x5b, 0xc7, 0x23, 0x61, 0xd6, 0x6c, 0x17, 0x86, 0xb7, 0x81,
	0x52, 0xef, 0xe3, 0xe4, 0x6a, 0xd2, 0x36, 0xfe, 0xcc, 0xe6, 0xc7, 0xb0, 0x9d, 0x43, 0xa8, 0xdb,
	0x38, 0x52, 0x92, 0xed, 0x40, 0x2f, 0x8d, 0x6f, 0x64, 0x44, 0x20, 0xd6, 0xe0, 0xe7, 0xb0, 0x31,
	0x8d, 0xaf, 0xc3, 0xe8, 0x63, 0x33, 0x3d, 0x85, 0x4d, 0xda, 0xbf, 0x36, 0xcd, 0x37, 0xd0, 0x7d,
	0xa3, 0x64, 0x52, 0x0b, 0xff, 0x19, 0x0c, 0x43, 0x35, 0x0b, 0xae, 0x96, 0x61, 0x64, 0xe0, 0x87,
	0x62, 0x10, 0xaa, 0xe7, 0x68, 0xf2, 0x07, 0x70, 0x1f, 0xb7, 0xbd, 0x8a, 0x7e, 0x8f, 0x89, 0x20,
	0xff, 0x15, 0xb6, 0x73, 0x17, 0xe5, 0xf4, 0x11, 0x5a, 0x05, 0x04, 0x76, 0x0c, 0xdd, 0x95, 0x0e,
	0x37, 0xc0, 0xe3, 0xd3, 0x9d, 0x93, 0xa2, 0xd6, 0x27, 0x08, 0x25, 0x4c, 0x84, 0xcb, 0x35, 0xd5,
	0xaa, 0xb9, 0x5c, 0xe7, 0x36, 0x97, 0x75, 0x51, 0xae, 0xaf, 0xa0, 0x87, 0xe1, 0x4a, 0x23, 0x76,
	0x1a, 0x11, 0x6d, 0x08, 0x3f, 0x83, 0xc1, 0x4f, 0x49, 0x7c, 0xb9, 0x90, 0xcb, 0xda, 0x83, 0xa3,
	0x54, 0x61, 0xba, 0x90, 0x24, 0xaa, 0x35, 0xf8, 0x0e, 0x30, 0xda, 0xe4, 0x53, 0xf9, 0x01, 0x3e,
	0x29, 0x78, 0x89, 0xcd, 0x99, 0xbe, 0x1a, 0xeb, 0x56, 0x1a, 0x1a, 0x09, 0x7d, 0x5a, 0x26, 0x44,
	0xdb, 0x44, 0x16, 0xa8, 0xab, 0xc3, 0x65, 0xf0, 0x84, 0xad, 0x63, 0xc8, 0xdf, 0x66, 0x59, 0x0b,
	0x7a, 0x67, 0xc4, 0x5b, 0x1e, 0x71, 0xf6, 0x04, 0x46, 0x2a, 0x0d, 0x52, 0xb9, 0x94, 0x51, 0x4a,
	0x47, 0xca, 0x1d, 0x6c, 0x0f, 0x20, 0x0d, 0x97, 0x72, 0xb6, 0x08, 0x97, 0x61, 0x3a, 0xe9, 0xe8,
	0x9f, 0x5b, 0x62, 0x84, 0x9e, 0x29, 0x3a, 0xf8, 0x1b, 0xd8, 0xbc, 0x58, 0x5d, 0xea, 0x95, 0xa3,
	0x33, 0x81, 0x01, 0x11, 0xa6, 0x2c, 0xce, 0x64, 0x8f, 0xa0, 0xaf, 0xe2, 0x55, 0x32, 0x77, 0xba,
	0x91, 0x85, 0x07, 0x58, 0x04, 0xd1, 0xb5, 0xc1, 0xd6, 0x07, 0xc0, 0x35, 0x3f, 0x84, 0x2d, 0x07,
	0x4b, 0xdc, 0xb7, 0xa0, 0x1d, 0x5e, 0x19, 0xc8, 0x9e, 0xd0, 0x2b, 0xfe, 0x6f, 0x0b, 0x98, 0x09,
	0x51, 0x2a, 0x8c, 0xa3, 0xd7, 0xef, 0x64, 0xf2, 0x2e, 0x94, 0xef, 0xcb, 0x61, 0xec, 0x73, 0xd8,
	0xa0, 0xfc, 0x33, 0xa3, 0x92, 0x4d, 0x3d, 0x26, 0xdf, 0x8f, 0x78, 0x9d, 0x47, 0xb0, 0xe9, 0x42,
	0xac, 0x3a, 0x96, 0x88, 0xdb, 0xf7, 0x8b, 0x11, 0xe9, 0x31, 0x8c, 0xb0, 0x36, 0x2c, 0x48, 0xd7,
	0x36, 0x13, 0x3a, 0x0c, 0x82, 0x3b, 0x41, 0x2f, 0x3f, 0x01, 0x6e, 0xd0, 0xb5, 0xbd, 0xd0, 0x32,
	0xaa, 0x74, 0xd2, 0x37, 0xc5, 0xad, 0x8b, 0x7d, 0x6a, 0x6c, 0x23, 0x85, 0x56, 0x78, 0xa5, 0x26,
	0x03, 0x92, 0xc2, 0x58, 0x08, 0x84, 0xd2, 0x4e, 0x86, 0x46, 0x66, 0xb3, 0xc6, 0xd8, 0xa5, 0x5c,
	0xc6, 0xc9, 0x87, 0xc9, 0x48, 0x7b, 0x3b, 0x82, 0x2c, 0x1e, 0xc1, 0x4e, 0x7e, 0xfe, 0x17, 0x81,
	0x92, 0x5a, 0xaa, 0xd5, 0xc2, 0xd4, 0xc3, 0x5c, 0x5b, 0xae, 0x1e, 0x70, 0xed, 0xe5, 0x6b, 0xd7,
	0xe6, 0xeb, 0xd4, 0xe6, 0xeb, 0x16, 0xf2, 0x7d, 0x09, 0x0f, 0xf3, 0x7c, 0x7e, 0x01, 0x96, 0x6f,
	0xe6, 0x9f, 0x16, 0x3c, 0x2a, 0x47, 0xd2, 0x25, 0x9e, 0xc3, 0x30, 0xa6, 0x9b, 0x32, 0x1b, 0xc6,
	0xa7, 0xbc, 0x5c, 0xf6, 0xd5, 0x3b, 0x15, 0xd9, 0x1e, 0xf6, 0x3d, 0x6c, 0xe0, 0x79, 0x66, 0x89,
	0x39, 0xaa, 0xeb, 0xe5, 0x2f, 0x9a, 0x31, 0x72, 0x5d, 0xc4, 0x78, 0x9e, 0xad, 0x95, 0x57, 0x8b,
	0x9d, 0x42, 0x2d, 0x1e, 0x80, 0x0e, 0x8b, 0x34, 0xfe, 0x1f, 0xab, 0xab, 0x6b, 0x7b, 0xd1, 0x43,
	0x01, 0xda, 0x25, 0xac, 0x87, 0xff, 0xdd, 0xf2, 0x65, 0xf0, 0x3a, 0x1d, 0xb5, 0x54, 0x37, 0xe1,
	0xad, 0x39, 0xd7, 0xa6, 0x30, 0x6b, 0x6c, 0x38, 0xdb, 0x37, 0x6d, 0xe3, 0xb4, 0x86, 0xdf, 0x22,
	0x9d, 0x6a, 0x8b, 0xd8, 0x7b, 0xea, 0x96, 0xef, 0xc9, 0x4c, 0x43, 0x2a, 0x30, 0x5c, 0x23, 0xb6,
	0x1e, 0xe4, 0xda, 0xd9, 0xb7, 0xcd, 0x6c, 0x0c, 0x9e, 0xfa, 0xda, 0x17, 0x46, 0xce, 0x4b, 0x18,
	0xab, 0xec, 0x17, 0x37, 0x75, 0xfe, 0x8f, 0xfc, 0xfe, 0x36, 0xcc, 0x3a, 0x8f, 0x57, 0x34, 0x28,
	0x7a, 0xc2, 0x1a, 0xd8, 0xae, 0x24, 0x50, 0x53, 0x51, 0x3c, 0xc0, 0xc7, 0x91, 0x22, 0x2c, 0x21,
	0xfe, 0x12, 0xba, 0x53, 0xec, 0x94, 0x3c, 0x74, 0x64, 0x5a, 0xd6, 0x0d, 0xb4, 0xb6, 0x37, 0x72,
	0xb5, 0x64, 0x9a, 0x0e, 0x52, 0x70, 0x92, 0x91, 0x89, 0xc0, 0x88, 0x52, 0x1a, 0xff, 0xb9, 0x2b,
	0x1f, 0xff, 0xd8, 0x96, 0xee, 0xdc, 0x95, 0xf1, 0x8f, 0x1b, 0x84, 0x0d, 0xe1, 0xdf, 0xc2, 0x16,
	0xbe, 0x06, 0x17, 0x5a, 0x7b, 0x0d, 0x11, 0xce, 0x55, 0xd3, 0x2b, 0x50, 0xa3, 0xc4, 0xb6, 0x56,
	0x22, 0x88, 0x6e, 0x42, 0x8d, 0x46, 0x6c, 0x7e, 0xd6, 0x27, 0x77, 0x9e, 0xac, 0x0d, 0x40, 0x65,
	0xe0, 0xc4, 0x68, 0xbf, 0xee, 0x41, 0xca, 0x29, 0x08, 0x6f, 0xc7, 0xe9, 0x5f, 0x43, 0x78, 0x38,
	0xb5, 0xd1, 0x2f, 0x6c, 0xf4, 0x05, 0xde, 0x95, 0xae, 0xdf, 0xd7, 0x30, 0x74, 0x1f, 0x10, 0xec,
	0xa0, 0x8c, 0x58, 0xfa, 0x3a, 0xd9, 0x3d, 0x6c, 0x0e, 0xa0, 0x2b, 0xba, 0xc7, 0xbe, 0x83, 0x9e,
	0xf9, 0x4e, 0x60, 0x4f, 0x2a, 0x8a, 0x79, 0x9f, 0x1f, 0xbb, 0x7b, 0x0d, 0xbf, 0x66, 0x38, 0x9a,
	0x98, 0x7b, 0xfe, 0xab, 0xc4, 0x4a, 0xdf, 0x0a, 0x55, 0x62, 0xe5, 0x2f, 0x87, 0x1c, 0x10, 0x2f,
	0xb9, 0x1e, 0xd0, 0xab, 0x88, 0x7a, 0x40, 0xbf, 0x3e, 0x34, 0xe0, 0x6f, 0x30, 0xf6, 0xde, 0x4c,
	0xc6, 0x1b, 0xde, 0x63, 0x9f, 0xe7, 0xd1, 0xda, 0x98, 0x1a, 0x64, 0xc3, 0xb6, 0x09, 0xd9, 0x27,
	0x7c, 0xb4, 0x36, 0x26, 0x43, 0x7e, 0x05, 0x7d, 0xfb, 0x4c, 0xb2, 0xbd, 0xda, 0x46, 0xce, 0xf0,
	0xf6, 0x9b, 0x7e, 0xce, 0xa0, 0x02, 0x7a, 0x71, 0xb3, 0xa1, 0xcd, 0x9e, 0x36, 0xcf, 0x06, 0x5f,
	0x84, 0x67, 0x77, 0x85, 0xd5, 0xa7, 0x30, 0x52, 0xac, 0x49, 0xe1, 0xab, 0xf1, 0xec, 0xae, 0xb0,
	0x2c, 0xc5, 0x14, 0x06, 0x34, 0x66, 0xd8, 0x7e, 0xb5, 0xba, 0xfd, 0x09, 0xb5, 0x7b, 0xd0, 0xf8,
	0xbb, 0x5f, 0x63, 0x6e, 0x90, 0x54, 0x6b, 0xac, 0x34, 0x75, 0xaa, 0x35, 0x56, 0x9e, 0x41, 0x44,
	0xcf, 0xce, 0x82, 0x1a, 0x7a, 0x85, 0xb1, 0x51, 0x43, 0xaf, 0x38, 0x44, 0xf8, 0xbd, 0xcb, 0xbe,
	0xf9, 0x1f, 0x72, 0xf6, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x82, 0x86, 0x0d, 0xa6, 0x0c,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LibraryCheckerServiceClient is the client API for LibraryCheckerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LibraryCheckerServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	UserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error)
	ProblemInfo(ctx context.Context, in *ProblemInfoRequest, opts ...grpc.CallOption) (*ProblemInfoResponse, error)
	ProblemList(ctx context.Context, in *ProblemListRequest, opts ...grpc.CallOption) (*ProblemListResponse, error)
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
	SubmissionInfo(ctx context.Context, in *SubmissionInfoRequest, opts ...grpc.CallOption) (*SubmissionInfoResponse, error)
	SubmissionList(ctx context.Context, in *SubmissionListRequest, opts ...grpc.CallOption) (*SubmissionListResponse, error)
	Rejudge(ctx context.Context, in *RejudgeRequest, opts ...grpc.CallOption) (*RejudgeResponse, error)
	LangList(ctx context.Context, in *LangListRequest, opts ...grpc.CallOption) (*LangListResponse, error)
	Ranking(ctx context.Context, in *RankingRequest, opts ...grpc.CallOption) (*RankingResponse, error)
}

type libraryCheckerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLibraryCheckerServiceClient(cc grpc.ClientConnInterface) LibraryCheckerServiceClient {
	return &libraryCheckerServiceClient{cc}
}

func (c *libraryCheckerServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/librarychecker.LibraryCheckerService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryCheckerServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/librarychecker.LibraryCheckerService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryCheckerServiceClient) UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, "/librarychecker.LibraryCheckerService/UserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryCheckerServiceClient) UserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, "/librarychecker.LibraryCheckerService/UserList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryCheckerServiceClient) ProblemInfo(ctx context.Context, in *ProblemInfoRequest, opts ...grpc.CallOption) (*ProblemInfoResponse, error) {
	out := new(ProblemInfoResponse)
	err := c.cc.Invoke(ctx, "/librarychecker.LibraryCheckerService/ProblemInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryCheckerServiceClient) ProblemList(ctx context.Context, in *ProblemListRequest, opts ...grpc.CallOption) (*ProblemListResponse, error) {
	out := new(ProblemListResponse)
	err := c.cc.Invoke(ctx, "/librarychecker.LibraryCheckerService/ProblemList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryCheckerServiceClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, "/librarychecker.LibraryCheckerService/Submit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryCheckerServiceClient) SubmissionInfo(ctx context.Context, in *SubmissionInfoRequest, opts ...grpc.CallOption) (*SubmissionInfoResponse, error) {
	out := new(SubmissionInfoResponse)
	err := c.cc.Invoke(ctx, "/librarychecker.LibraryCheckerService/SubmissionInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryCheckerServiceClient) SubmissionList(ctx context.Context, in *SubmissionListRequest, opts ...grpc.CallOption) (*SubmissionListResponse, error) {
	out := new(SubmissionListResponse)
	err := c.cc.Invoke(ctx, "/librarychecker.LibraryCheckerService/SubmissionList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryCheckerServiceClient) Rejudge(ctx context.Context, in *RejudgeRequest, opts ...grpc.CallOption) (*RejudgeResponse, error) {
	out := new(RejudgeResponse)
	err := c.cc.Invoke(ctx, "/librarychecker.LibraryCheckerService/Rejudge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryCheckerServiceClient) LangList(ctx context.Context, in *LangListRequest, opts ...grpc.CallOption) (*LangListResponse, error) {
	out := new(LangListResponse)
	err := c.cc.Invoke(ctx, "/librarychecker.LibraryCheckerService/LangList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryCheckerServiceClient) Ranking(ctx context.Context, in *RankingRequest, opts ...grpc.CallOption) (*RankingResponse, error) {
	out := new(RankingResponse)
	err := c.cc.Invoke(ctx, "/librarychecker.LibraryCheckerService/Ranking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LibraryCheckerServiceServer is the server API for LibraryCheckerService service.
type LibraryCheckerServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	UserInfo(context.Context, *UserInfoRequest) (*UserInfoResponse, error)
	UserList(context.Context, *UserListRequest) (*UserListResponse, error)
	ProblemInfo(context.Context, *ProblemInfoRequest) (*ProblemInfoResponse, error)
	ProblemList(context.Context, *ProblemListRequest) (*ProblemListResponse, error)
	Submit(context.Context, *SubmitRequest) (*SubmitResponse, error)
	SubmissionInfo(context.Context, *SubmissionInfoRequest) (*SubmissionInfoResponse, error)
	SubmissionList(context.Context, *SubmissionListRequest) (*SubmissionListResponse, error)
	Rejudge(context.Context, *RejudgeRequest) (*RejudgeResponse, error)
	LangList(context.Context, *LangListRequest) (*LangListResponse, error)
	Ranking(context.Context, *RankingRequest) (*RankingResponse, error)
}

// UnimplementedLibraryCheckerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLibraryCheckerServiceServer struct {
}

func (*UnimplementedLibraryCheckerServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedLibraryCheckerServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedLibraryCheckerServiceServer) UserInfo(ctx context.Context, req *UserInfoRequest) (*UserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfo not implemented")
}
func (*UnimplementedLibraryCheckerServiceServer) UserList(ctx context.Context, req *UserListRequest) (*UserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserList not implemented")
}
func (*UnimplementedLibraryCheckerServiceServer) ProblemInfo(ctx context.Context, req *ProblemInfoRequest) (*ProblemInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProblemInfo not implemented")
}
func (*UnimplementedLibraryCheckerServiceServer) ProblemList(ctx context.Context, req *ProblemListRequest) (*ProblemListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProblemList not implemented")
}
func (*UnimplementedLibraryCheckerServiceServer) Submit(ctx context.Context, req *SubmitRequest) (*SubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (*UnimplementedLibraryCheckerServiceServer) SubmissionInfo(ctx context.Context, req *SubmissionInfoRequest) (*SubmissionInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmissionInfo not implemented")
}
func (*UnimplementedLibraryCheckerServiceServer) SubmissionList(ctx context.Context, req *SubmissionListRequest) (*SubmissionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmissionList not implemented")
}
func (*UnimplementedLibraryCheckerServiceServer) Rejudge(ctx context.Context, req *RejudgeRequest) (*RejudgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rejudge not implemented")
}
func (*UnimplementedLibraryCheckerServiceServer) LangList(ctx context.Context, req *LangListRequest) (*LangListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LangList not implemented")
}
func (*UnimplementedLibraryCheckerServiceServer) Ranking(ctx context.Context, req *RankingRequest) (*RankingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ranking not implemented")
}

func RegisterLibraryCheckerServiceServer(s *grpc.Server, srv LibraryCheckerServiceServer) {
	s.RegisterService(&_LibraryCheckerService_serviceDesc, srv)
}

func _LibraryCheckerService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryCheckerServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/librarychecker.LibraryCheckerService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryCheckerServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryCheckerService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryCheckerServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/librarychecker.LibraryCheckerService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryCheckerServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryCheckerService_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryCheckerServiceServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/librarychecker.LibraryCheckerService/UserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryCheckerServiceServer).UserInfo(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryCheckerService_UserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryCheckerServiceServer).UserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/librarychecker.LibraryCheckerService/UserList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryCheckerServiceServer).UserList(ctx, req.(*UserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryCheckerService_ProblemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProblemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryCheckerServiceServer).ProblemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/librarychecker.LibraryCheckerService/ProblemInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryCheckerServiceServer).ProblemInfo(ctx, req.(*ProblemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryCheckerService_ProblemList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProblemListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryCheckerServiceServer).ProblemList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/librarychecker.LibraryCheckerService/ProblemList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryCheckerServiceServer).ProblemList(ctx, req.(*ProblemListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryCheckerService_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryCheckerServiceServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/librarychecker.LibraryCheckerService/Submit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryCheckerServiceServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryCheckerService_SubmissionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmissionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryCheckerServiceServer).SubmissionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/librarychecker.LibraryCheckerService/SubmissionInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryCheckerServiceServer).SubmissionInfo(ctx, req.(*SubmissionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryCheckerService_SubmissionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmissionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryCheckerServiceServer).SubmissionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/librarychecker.LibraryCheckerService/SubmissionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryCheckerServiceServer).SubmissionList(ctx, req.(*SubmissionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryCheckerService_Rejudge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejudgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryCheckerServiceServer).Rejudge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/librarychecker.LibraryCheckerService/Rejudge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryCheckerServiceServer).Rejudge(ctx, req.(*RejudgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryCheckerService_LangList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LangListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryCheckerServiceServer).LangList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/librarychecker.LibraryCheckerService/LangList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryCheckerServiceServer).LangList(ctx, req.(*LangListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryCheckerService_Ranking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryCheckerServiceServer).Ranking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/librarychecker.LibraryCheckerService/Ranking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryCheckerServiceServer).Ranking(ctx, req.(*RankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LibraryCheckerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "librarychecker.LibraryCheckerService",
	HandlerType: (*LibraryCheckerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _LibraryCheckerService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _LibraryCheckerService_Login_Handler,
		},
		{
			MethodName: "UserInfo",
			Handler:    _LibraryCheckerService_UserInfo_Handler,
		},
		{
			MethodName: "UserList",
			Handler:    _LibraryCheckerService_UserList_Handler,
		},
		{
			MethodName: "ProblemInfo",
			Handler:    _LibraryCheckerService_ProblemInfo_Handler,
		},
		{
			MethodName: "ProblemList",
			Handler:    _LibraryCheckerService_ProblemList_Handler,
		},
		{
			MethodName: "Submit",
			Handler:    _LibraryCheckerService_Submit_Handler,
		},
		{
			MethodName: "SubmissionInfo",
			Handler:    _LibraryCheckerService_SubmissionInfo_Handler,
		},
		{
			MethodName: "SubmissionList",
			Handler:    _LibraryCheckerService_SubmissionList_Handler,
		},
		{
			MethodName: "Rejudge",
			Handler:    _LibraryCheckerService_Rejudge_Handler,
		},
		{
			MethodName: "LangList",
			Handler:    _LibraryCheckerService_LangList_Handler,
		},
		{
			MethodName: "Ranking",
			Handler:    _LibraryCheckerService_Ranking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/library_checker.proto",
}
