// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/library_checker.proto

package librarychecker

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LangListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LangListRequest) Reset()         { *m = LangListRequest{} }
func (m *LangListRequest) String() string { return proto.CompactTextString(m) }
func (*LangListRequest) ProtoMessage()    {}
func (*LangListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{0}
}

func (m *LangListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LangListRequest.Unmarshal(m, b)
}
func (m *LangListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LangListRequest.Marshal(b, m, deterministic)
}
func (m *LangListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LangListRequest.Merge(m, src)
}
func (m *LangListRequest) XXX_Size() int {
	return xxx_messageInfo_LangListRequest.Size(m)
}
func (m *LangListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LangListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LangListRequest proto.InternalMessageInfo

type Lang struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lang) Reset()         { *m = Lang{} }
func (m *Lang) String() string { return proto.CompactTextString(m) }
func (*Lang) ProtoMessage()    {}
func (*Lang) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{1}
}

func (m *Lang) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lang.Unmarshal(m, b)
}
func (m *Lang) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lang.Marshal(b, m, deterministic)
}
func (m *Lang) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lang.Merge(m, src)
}
func (m *Lang) XXX_Size() int {
	return xxx_messageInfo_Lang.Size(m)
}
func (m *Lang) XXX_DiscardUnknown() {
	xxx_messageInfo_Lang.DiscardUnknown(m)
}

var xxx_messageInfo_Lang proto.InternalMessageInfo

func (m *Lang) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Lang) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Lang) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LangListResponse struct {
	Langs                []*Lang  `protobuf:"bytes,1,rep,name=langs,proto3" json:"langs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LangListResponse) Reset()         { *m = LangListResponse{} }
func (m *LangListResponse) String() string { return proto.CompactTextString(m) }
func (*LangListResponse) ProtoMessage()    {}
func (*LangListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9accbd90656ef5bc, []int{2}
}

func (m *LangListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LangListResponse.Unmarshal(m, b)
}
func (m *LangListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LangListResponse.Marshal(b, m, deterministic)
}
func (m *LangListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LangListResponse.Merge(m, src)
}
func (m *LangListResponse) XXX_Size() int {
	return xxx_messageInfo_LangListResponse.Size(m)
}
func (m *LangListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LangListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LangListResponse proto.InternalMessageInfo

func (m *LangListResponse) GetLangs() []*Lang {
	if m != nil {
		return m.Langs
	}
	return nil
}

func init() {
	proto.RegisterType((*LangListRequest)(nil), "librarychecker.LangListRequest")
	proto.RegisterType((*Lang)(nil), "librarychecker.Lang")
	proto.RegisterType((*LangListResponse)(nil), "librarychecker.LangListResponse")
}

func init() { proto.RegisterFile("proto/library_checker.proto", fileDescriptor_9accbd90656ef5bc) }

var fileDescriptor_9accbd90656ef5bc = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0xc9, 0x4c, 0x2a, 0x4a, 0x2c, 0xaa, 0x8c, 0x4f, 0xce, 0x48, 0x4d, 0xce, 0x4e,
	0x2d, 0xd2, 0x03, 0x8b, 0x0a, 0xf1, 0x41, 0x85, 0xa1, 0xa2, 0x4a, 0x82, 0x5c, 0xfc, 0x3e, 0x89,
	0x79, 0xe9, 0x3e, 0x99, 0xc5, 0x25, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x4a, 0x2e, 0x5c,
	0x2c, 0x20, 0x21, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20,
	0x20, 0x4b, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x09, 0x2c, 0x02, 0x66, 0x0b,
	0x49, 0x70, 0xb1, 0x97, 0xa5, 0x16, 0x15, 0x67, 0xe6, 0xe7, 0x49, 0x30, 0x83, 0x85, 0x61, 0x5c,
	0x25, 0x3b, 0x2e, 0x01, 0x84, 0xc1, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x5a, 0x5c, 0xac,
	0x39, 0x40, 0xb1, 0x62, 0xa0, 0xa1, 0xcc, 0x1a, 0xdc, 0x46, 0x22, 0x7a, 0xa8, 0x8e, 0xd1, 0x03,
	0x69, 0x08, 0x82, 0x28, 0x31, 0xca, 0xe0, 0x12, 0xf5, 0x81, 0xc8, 0x3a, 0x43, 0x64, 0x83, 0x53,
	0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0xfc, 0xb9, 0x38, 0x60, 0x06, 0x0b, 0xc9, 0x63, 0x33, 0x01,
	0xc9, 0x2f, 0x52, 0x0a, 0xb8, 0x15, 0x40, 0xdc, 0xa4, 0xc4, 0x90, 0xc4, 0x06, 0x0e, 0x19, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x96, 0xd6, 0x5e, 0x38, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LibraryCheckerServiceClient is the client API for LibraryCheckerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LibraryCheckerServiceClient interface {
	LangList(ctx context.Context, in *LangListRequest, opts ...grpc.CallOption) (*LangListResponse, error)
}

type libraryCheckerServiceClient struct {
	cc *grpc.ClientConn
}

func NewLibraryCheckerServiceClient(cc *grpc.ClientConn) LibraryCheckerServiceClient {
	return &libraryCheckerServiceClient{cc}
}

func (c *libraryCheckerServiceClient) LangList(ctx context.Context, in *LangListRequest, opts ...grpc.CallOption) (*LangListResponse, error) {
	out := new(LangListResponse)
	err := c.cc.Invoke(ctx, "/librarychecker.LibraryCheckerService/LangList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LibraryCheckerServiceServer is the server API for LibraryCheckerService service.
type LibraryCheckerServiceServer interface {
	LangList(context.Context, *LangListRequest) (*LangListResponse, error)
}

// UnimplementedLibraryCheckerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLibraryCheckerServiceServer struct {
}

func (*UnimplementedLibraryCheckerServiceServer) LangList(ctx context.Context, req *LangListRequest) (*LangListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LangList not implemented")
}

func RegisterLibraryCheckerServiceServer(s *grpc.Server, srv LibraryCheckerServiceServer) {
	s.RegisterService(&_LibraryCheckerService_serviceDesc, srv)
}

func _LibraryCheckerService_LangList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LangListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryCheckerServiceServer).LangList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/librarychecker.LibraryCheckerService/LangList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryCheckerServiceServer).LangList(ctx, req.(*LangListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LibraryCheckerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "librarychecker.LibraryCheckerService",
	HandlerType: (*LibraryCheckerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LangList",
			Handler:    _LibraryCheckerService_LangList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/library_checker.proto",
}
