title = 'A + B'
timelimit = 2.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/32"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "random.cpp"
    number = 3

[[solutions]]
    name = "wa.cpp"
    expect = "WA"
[[solutions]]
    name = "ac_func.cpp"
    function = true

[params]
    A_AND_B_MAX = 1_000_000_000
