/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/ranking": {
    /** Get ranking */
    get: operations["getRanking"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    UserStatistics: {
      name: string;
      /** Format: int32 */
      count: number;
    };
    RankingResponse: {
      statistics: components["schemas"]["UserStatistics"][];
      /** Format: int32 */
      count: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** Get ranking */
  getRanking: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RankingResponse"];
        };
      };
    };
  };
}
