name: Cloud-Function-Deploy

on:
  push:
    branches:
      - master
      - test/cf

jobs:
  judge-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: projects/190778459730/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
        service_account: cloud-function-deployer@library-checker-project.iam.gserviceaccount.com
        token_format: access_token

    - id: cloud-function-deploy
      name: Deploy cloud function
      run: gcloud functions deploy instances-notice --runtime=python310 --source=. --entry-point=main_handler --trigger-topic=gce_instance_status_visor --set-secrets "HOOK_URL=instances-notice-hook-url:latest" --service-account=instances-notify-executor@library-checker-project.iam.gserviceaccount.com
      working-directory: ./tools/bot/instances-notify
