name: Lint Storage

on:
  push:
    branches:
      - master
    paths:
      - 'storage/**'
      - 'database/**'  # storage depends on database
      - '.github/workflows/lint-storage.yml'
  pull_request:
    paths:
      - 'storage/**'
      - 'database/**'  # storage depends on database
      - '.github/workflows/lint-storage.yml'

jobs:
  lint-storage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: ./run_protoc.sh

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: gofmt (storage)
      working-directory: ./storage
      run: |
        out=$(gofmt -l -s .)
        if [ -n "$out" ]; then
          echo 'The following files are not gofmt-ed:'
          echo "$out"
          echo
          echo 'Please run: gofmt -s -w ./storage'
          exit 1
        fi

    - name: golangci-lint (storage)
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        working-directory: ./storage
