name: Lint Executor

on:
  push:
    branches:
      - master
    paths:
      - 'executor/**'
      - 'langs/**'  # executor uses langs for testing
      - '.github/workflows/lint-executor.yml'
  pull_request:
    paths:
      - 'executor/**'
      - 'langs/**'  # executor uses langs for testing
      - '.github/workflows/lint-executor.yml'

jobs:
  lint-executor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: ./run_protoc.sh

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: gofmt (executor)
      working-directory: ./executor
      run: |
        out=$(gofmt -l -s .)
        if [ -n "$out" ]; then
          echo 'The following files are not gofmt-ed:'
          echo "$out"
          echo
          echo 'Please run: gofmt -s -w ./executor'
          exit 1
        fi

    - name: golangci-lint (executor)
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        working-directory: ./executor
