name: Lint Database

on:
  push:
    branches:
      - master
    paths:
      - 'database/**'
      - '.github/workflows/lint-database.yml'
  pull_request:
    paths:
      - 'database/**'
      - '.github/workflows/lint-database.yml'

jobs:
  lint-database:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: ./run_protoc.sh

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'


    - name: golangci-lint (database)
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        working-directory: ./database
        args: --config ../.golangci.yml
