name: Lint Go Format

on:
  pull_request:
    paths:
      - "**/*.go"
  push:
    branches: [ master ]
    paths:
      - "**/*.go"

jobs:
  gofmt:
    name: gofmt check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Run gofmt (check only)
        run: |
          out=$(gofmt -l -s .)
          if [ -n "$out" ]; then
            echo 'The following files are not gofmt-ed:'
            echo "$out"
            echo
            echo 'Please run: gofmt -s -w .'
            exit 1
          fi

