name: Lint Langs

on:
  push:
    branches:
      - master
    paths:
      - 'langs/**'
      - '.github/workflows/lint-langs.yml'
  pull_request:
    paths:
      - 'langs/**'
      - '.github/workflows/lint-langs.yml'

jobs:
  lint-langs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: ./run_protoc.sh

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: gofmt (langs)
      working-directory: ./langs
      run: |
        out=$(gofmt -l -s .)
        if [ -n "$out" ]; then
          echo 'The following files are not gofmt-ed:'
          echo "$out"
          echo
          echo 'Please run: gofmt -s -w ./langs'
          exit 1
        fi

    - name: golangci-lint (langs)
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        working-directory: ./langs
