name: Lint Judge

on:
  push:
    branches:
      - master
    paths:
      - 'judge/**'
      - 'database/**'  # judge depends on database
      - 'executor/**'  # judge depends on executor
      - 'langs/**'     # judge depends on langs
      - 'storage/**'   # judge depends on storage
      - '.github/workflows/lint-judge.yml'
  pull_request:
    paths:
      - 'judge/**'
      - 'database/**'  # judge depends on database
      - 'executor/**'  # judge depends on executor
      - 'langs/**'     # judge depends on langs
      - 'storage/**'   # judge depends on storage
      - '.github/workflows/lint-judge.yml'

jobs:
  lint-judge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: ./run_protoc.sh

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: gofmt (judge)
      working-directory: ./judge
      run: |
        out=$(gofmt -l -s .)
        if [ -n "$out" ]; then
          echo 'The following files are not gofmt-ed:'
          echo "$out"
          echo
          echo 'Please run: gofmt -s -w ./judge'
          exit 1
        fi

    - name: golangci-lint (judge)
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        working-directory: ./judge
