name: Lint Langs

on:
  push:
    branches:
      - master
    paths:
      - 'langs/**'
      - '.github/workflows/lint-langs.yml'
  pull_request:
    paths:
      - 'langs/**'
      - '.github/workflows/lint-langs.yml'

jobs:
  lint-langs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: ./run_protoc.sh

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'


    - name: golangci-lint (langs)
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        working-directory: ./langs
