name: Lint Executor

on:
  push:
    branches:
      - master
    paths:
      - 'executor/**'
      - 'langs/**'  # executor uses langs for testing
      - '.github/workflows/lint-executor.yml'
  pull_request:
    paths:
      - 'executor/**'
      - 'langs/**'  # executor uses langs for testing
      - '.github/workflows/lint-executor.yml'

jobs:
  lint-executor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: ./run_protoc.sh

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'


    - name: golangci-lint (executor)
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        working-directory: ./executor
