name: Prod-Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'
      - '.github/workflows/prod-frontend-deploy.yml'
      - '.github/workflows/test-frontend.yml'

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      env: prod
