name: Prod-Frontend-Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - 'restapi/openapi/**'
      - '.github/workflows/frontend-deploy.yml'
      - '.github/workflows/prod-frontend-deploy.yml'
  workflow_call:

jobs:
  frontend-deploy:
    uses: ./.github/workflows/frontend-deploy.yml
    secrets: inherit
    with:
      env: prod
