name: Test Judge

on:
  push:
    branches:
      - master
    paths:
      - 'judge/**'
      - 'database/**'  # judge depends on database
      - 'executor/**'  # judge depends on executor
      - 'langs/**'     # judge depends on langs
      - 'storage/**'   # judge depends on storage
      - '.github/workflows/test-judge.yml'
  pull_request:
    paths:
      - 'judge/**'
      - 'database/**'  # judge depends on database
      - 'executor/**'  # judge depends on executor
      - 'langs/**'     # judge depends on langs
      - 'storage/**'   # judge depends on storage
      - '.github/workflows/test-judge.yml'

jobs:
  test-judge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: ./run_protoc.sh

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run docker compose
      run: docker compose up -d --build --wait

    - name: Install crun
      run: sudo ./packer/base/crun-install.sh

    - name: Prepare docker config
      run: sudo cp ./packer/base/docker-daemon.json /etc/docker/daemon.json

    - name: Restart docker
      run: sudo service docker restart
          
    - name: Build lang images
      run: ./build.sh
      working-directory: ./langs

    - name: Judge module test
      run: go test -v .
      working-directory: ./judge