name: Test Storage

on:
  push:
    branches:
      - master
    paths:
      - 'storage/**'
      - 'database/**'  # storage depends on database
      - '.github/workflows/test-storage.yml'
  pull_request:
    paths:
      - 'storage/**'
      - 'database/**'  # storage depends on database
      - '.github/workflows/test-storage.yml'

jobs:
  test-storage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: ./run_protoc.sh

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Run docker compose
      run: docker compose up -d --build --wait

    - name: Storage module test
      run: go test . -v
      working-directory: ./storage
