name: Test API

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'
      - 'database/**'  # api depends on database
      - 'langs/**'     # api depends on langs
      - '.github/workflows/test-api.yml'
  pull_request:
    paths:
      - 'api/**'
      - 'database/**'  # api depends on database
      - 'langs/**'     # api depends on langs
      - '.github/workflows/test-api.yml'

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: ./run_protoc.sh

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run docker compose
      run: docker compose up -d --build --wait

    - name: API module test
      run: go test . -v
      working-directory: ./api