name: Test Uploader

on:
  push:
    branches:
      - master
    paths:
      - 'uploader/**'
      - 'database/**'  # uploader depends on database
      - 'storage/**'   # uploader depends on storage
      - '.github/workflows/test-uploader.yml'
  pull_request:
    paths:
      - 'uploader/**'
      - 'database/**'  # uploader depends on database
      - 'storage/**'   # uploader depends on storage
      - '.github/workflows/test-uploader.yml'

jobs:
  test-uploader:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: ./run_protoc.sh

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run docker compose
      run: docker compose up -d --build --wait

    - name: Uploader module test
      run: go test . -v
      working-directory: ./uploader