name: Test Frontend

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - 'restapi/openapi/**'
      - '.github/workflows/test-frontend.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - 'restapi/openapi/**'
      - '.github/workflows/test-frontend.yml'

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24"

      - run: npm ci
        working-directory: ./frontend
      - run: npm run openapi:gen
        working-directory: ./frontend
      - run: npm run coverage
        working-directory: ./frontend
      - run: npm run prettier:check
        working-directory: ./frontend
      - run: npm run lint
        working-directory: ./frontend
      - run: npm run build
        working-directory: ./frontend
