name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Detect changed files
      uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          database:
            - 'database/**'
            - '.github/workflows/test.yml'
          api:
            - 'api/**'
            - '.github/workflows/test.yml'
          storage:
            - 'storage/**'
            - '.github/workflows/test.yml'
          uploader:
            - 'uploader/**'
            - '.github/workflows/test.yml'
          judge:
            - 'judge/**'
            - '.github/workflows/test.yml'

    - run: ./run_protoc.sh

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run docker compose
      run: docker compose up -d --build --wait

    - name: Database module test
      if: steps.changes.outputs.database == 'true'
      run: go test . -v
      working-directory: ./database

    - name: API module test
      if: steps.changes.outputs.api == 'true'
      run: go test . -v
      working-directory: ./api

    - name: Storage module test
      if: steps.changes.outputs.storage == 'true'
      run: go test . -v
      working-directory: ./storage

    - name: Uploader module test
      if: steps.changes.outputs.uploader == 'true'
      run: go test . -v
      working-directory: ./uploader

    - name: Install crun
      if: steps.changes.outputs.judge == 'true'
      run: sudo ./packer/base/crun-install.sh

    - name: Prepare docker config
      if: steps.changes.outputs.judge == 'true'
      run: sudo cp ./packer/base/docker-daemon.json /etc/docker/daemon.json

    - name: Restart docker
      if: steps.changes.outputs.judge == 'true'
      run: sudo service docker restart
          
    - name: Build lang images
      if: steps.changes.outputs.judge == 'true'
      run: ./build.sh
      working-directory: ./langs

    - name: Judge module test
      if: steps.changes.outputs.judge == 'true'
      run: go test -v .
      working-directory: ./judge